### ISSUE TITLE
Remaining 1.2.1 error concerning parms2BIDS

### ISSUE THREAD

**Issue by HenkMutsaerts** [ExploreASL/ExploreASL#110]
Error in Philips_2DEPI_FLAIRsegmentation_PWI4D_QuantificationParameters_LoQ:

1) xASL_bids_parms2BIDS.m didn't deal nicely with vectors, it expected scalar inputs only. This is fixed now

2) when SliceReadoutTime = 'shortestTR' (which is the case in the 4th TestDataSet), xASL_adm_LoadParms.m erroneously amplifies the SliceReadoutTime by 1000. Check in xASL_quant_M0.m or xASL_quant_SinglePLD.m, which now both use xASL_quant_SliceReadoutTime_ShortestTR.m. Inside the code it should all be in ms, outside the code in seconds. xASL_adm_LoadParms somehow expects SliceReadoutTime to be in seconds where it is saved internally in ms by xASL_quant_SliceReadoutTime_Shortest_TR.m

**Comment by jan-petr** [comment]
Two further issues
1) ASL_quant_SliceReadoutTime_ShortestTR crashes on checking if SliceReadoutTime is within range when it is a vector and not a scalar.
2) The SliceReadoutTime calculated for shortestTR fails on conversion from ms to s and back producing values over 1000s.

**Comment by jan-petr** [comment]
Fixed the second problem as well. The issue was that sliceReadoutTIme was given as 'shortestTR'. And BIDS2XASL conversion tried to convert this from ms to s which corrupted the string. 

This is now fixed in BIDS2PARMS, all strings are skipped in the ms to s conversion. For BIDS2XASL, a warning is reported as sliceReadoutTime has to be a scalar, not a string.

So we have to additionally fix this in the testDataset - Philips_2DEPI_FLAIRsegmentation_PWI4D_QuantificationParameters_LoQ.
Either the ASL and M0.json need to have the 'shortestTR' replaced by the real value (calculated as 21.05ms) in each individual JSON, or it has to be removed from the individual JSON (that are in BIDS) and this has to be put in the datapar.json which is in the xASL format.

**Comment by HenkMutsaerts** [comment]
Good point, but this is to test the option of having the "shortestTR", which is there as the SliceReadoutTime will differ slightly between scans/subjects. In the future, it is probably better to remove this parameter and write a function that gets this as average from the population and indeed use the same SliceReadoutTime for all participants?

I will now move the "shortestTR" from the JSON sidecar to the DataPar, OK?

**Comment by jan-petr** [comment]
Yes. I agree that we should leave this testing option there, at least for some time.

Yes - move it please to the DataPar - that's an xASL structure and SliceReadoutTime='shortestTR' is a valid option and won't produce any warnings and will work completely correctly.

Regarding '\\\\' - thanks for fixing - AFAIK - this is problem only for certain OSes.

PS: I have in my head a concept for turning the BIDS example script to a full Import_BIDS  script to replace the Import_JSON, I will write a BIDS2xASL script. And I will write a unit testing script that compares the DCM2BIDS conversion of the ~40 testdatasets with the output I have produced for Patricia and that was 100% validated by me, her and the BIDS validator (the plan would be to compare the files structure, NII content, and all JSONs parameters.
