### ISSUE TITLE
Separate import from data loading/processing

### ISSUE THREAD

**Issue by jan-petr** [ExploreASL/ExploreASL#1115]
### Description

Separate import from data loading/processing

### Release notes

Finish separation of import from data loading andprocessing.

**Comment by HenkMutsaerts** [comment]
@jan-petr we need to merge these things, otherwise we become inefficient. E.g., I noted today that with BIDS2Legacy, for each subject it gives a warning about dataPar.json existence, which should be subject-independent and issue only a single warning. But now I don't know if this was fixed already in this issue  :)

**Comment by HenkMutsaerts** [comment]
- [ ] Also, when just loading in data: `ExploreASL('path2datasetroot');`
it takes a long time per subject to verify that the data were already converted from BIDS2Legacy

**Comment by jan-petr** [comment]
Yes - we forgot about this one. And I have previously checked it all and tested it and 'approved' - we should always create a PR when we start reviewing stuff. That way, we won't miss out on these things.

Anyway - I have checked that there are still no conflicts. And I have previously debugged it, so I would just merge it now. I wouldn't do more edits in this branch. Those things mentioned above - if they are still relevant, then please create a new issue.
