### ISSUE TITLE
Residual 1.2.1: masking issue in 4th example

### ISSUE THREAD

**Issue by HenkMutsaerts** [ExploreASL/ExploreASL#115]
Example 

/TestCasesProcessed/Philips_2DEPI_FLAIRsegmentation_PWI4D_QuantificationParameters_LoQ

gives me weird masking of the M0, resulting in division artifacts as shown below. Somehow not sufficient iterations are done for replacing everything with NaNs and extrapolating the M0 smooth biasfield. There is perhaps an issue with the maximum that is checked for this, and/or the T2 segmentation used for the M0 segmentation goes incorrectly with the low quality (perhaps we should test this case only at high quality?).

**Comment by jan-petr** [comment]
Tell me more or send images - this works rather nicely on my side (or I haven't noticed anything wrong).

**Comment by jan-petr** [comment]
At least the final CBF numbers are fine - for you as well?

**Comment by jan-petr** [comment]
I fully understand what you mean now. And I see that as well in my results. I will try to fix it.

If easy - for 1.2.1.
If this proves to be really complex than for 1.3.0.

Last question - is this new, or we saw it in previous releases as well, or you don't know when this occurred?

**Comment by jan-petr** [comment]
First finding - the problem is definitively not with number of smoothing and extrapolating iterations. Simply because they are not executed - the whole dataset is configured for ConventionalM0processing :D

But the mask_m0 still nicely have the NaNs around the head, so there still shouldn't be the division artifacts - but we have probably changed the visualization procedure so that's no more compatible with the ConventionalM0.

**Comment by jan-petr** [comment]
Found a solution. In the ProcessM0 submodule, the NaNs in the M0 mask a lost during the process, leaving them as simple zeros.

See my trivial solution to that in the code. If you don't like replacing zeros by NaNs in the mask, then we will have to produce a separate NaN mask and transform that by the side.

Either way - this solves the problem.

![QC](https://user-images.githubusercontent.com/29886537/92235234-a0a5d280-eeb3-11ea-87ba-86faf5ca26ac.png)

**Comment by HenkMutsaerts** [comment]
* I don't think this is new, probably we didn't inspect this before :)
* Good point about the Conventional M0 processing, then there is actually no issue
* setting zeroes to NaN is tricky, as NaNs are reserved for "outside FoV/mask" and zeroes not. But here it makes sense.
* One thing I don't understand: outside the CBF image we divide by NaNs, so this should not give any values, whereas we do see a rim around the brain on the CBF image as if this wasn't divided. Can you check what was the case here?

**Comment by jan-petr** [comment]
> * I don't think this is new, probably we didn't inspect this before :)

:) OK 

> * setting zeroes to NaN is tricky, as NaNs are reserved for "outside FoV/mask" and zeroes not. But here it makes sense.

Totally agree - that's why I wanted to have you opinion on it.

> * One thing I don't understand: outside the CBF image we divide by NaNs, so this should not give any values, whereas we do see a rim around the brain on the CBF image as if this wasn't divided. Can you check what was the case here?

Yes, outside of CBF we divide by NaNs and this should give blank space. There's a rim around CBF - but it *was* correctly divided. Just the M0 was not NaN but had a reasonable value. You could see that the masked M0 is slightly larger than CBF image, so the zeros (then replaced by NaNs) in the M0-mask are slightly bigger than the CBF image. This creates the rim. We would have to change the M0 thresholding to have a more tight mask and no rim.

But I would create a new issue for that if that's needed.

**Comment by HenkMutsaerts** [comment]
OK it looked a bit different, but if you are certain this rim is correctly divided then we can keep this. This method doesn't really work, which is why we use our own ExploreASL improved method :) So I agree!
