### ISSUE TITLE
xASL_adm_GzipAllFiles bug on windows (normal and compiled)

### ISSUE THREAD

**Issue by MichaelStritt** [ExploreASL/ExploreASL#118]
Error message from rerun:
```
...
060_GetMotionStatistics has already been performed, skipping...
070_GetROIstatistics has already been performed, skipping...
Sorting ASLCheck QC images for spatial CoV:100%
080_SortBySpatialCoV was perform100%
"i" kann syntaktisch an dieser Stelle nicht verarbeitet werden. 
```
Problematic code section in **xASL_adm_GzipAllFiles**:
```
if bUseLinux
  PathToSearch = xASL_adm_UnixPath(ROOT);
  system(['for i in `find ' PathToSearch '/* | grep -E \.nii$`; do gzip -1 -f -q -v "$i"; done'], '-echo');
  return;
end
```

**Comment by jan-petr** [comment]
A few questions. It crashed in deployed linux version?
My guess is that the deployed version treats the string differently than the Matlab version.
While Matlab has ' as the ultimate string delimiter and " is just put inside. The deployed version takes " as a string delimiter as well and instead of having the " inside the string it takes it as an end of string. So the second i in "$i" is not passed to command line, but tried to be evaluated.

Simply try replacing the string between the [ ] with the following
['for i in ' 96 'find ' PathToSearch '/* | grep -E \.nii$' 96 '; do gzip -1 -f -q -v ' 34 '$i' 34 '; done']

**Comment by HenkMutsaerts** [comment]
I see the error:

    if nargin<3 || isempty(bUseLinux) && (isunix || ismac)
        bUseLinux = true;

should have been

    if (nargin<3 || isempty(bUseLinux)) && (isunix || ismac)
        bUseLinux = true;

**Comment by HenkMutsaerts** [comment]
I will edit this one and do a PR!

**Comment by jan-petr** [comment]
You can also add the edit proposed above to avoid future issues...

**Comment by HenkMutsaerts** [comment]
Why would the deployed version take " as strings? How is _34_ a replacement of a _'_?

**Comment by jan-petr** [comment]
I mean character array. It starts with '. And obviously, in the deployed version " is taken as an end of the character array. That's why the i in "$i" is tried to be evaluated as a variable and not part as char - I think that this is what happens. Although the real problem was that it incorrectly evaluated bUseLinux in the first place.

34 is ASCII code for " - so you can use that for replacement.

**Comment by HenkMutsaerts** [comment]
OK cool. I would see if this is indeed the case. " can be used by newer Matlab versions in addition to '. I haven't seen a different behavior here upon deploying, I would find that very weird. Is the ASCII code understood in this location? Always? In every OS/Matlab version? :)

**Comment by MichaelStritt** [comment]
Tested on windows server in normal Matlab mode:
```
070_GetROIstatistics was performed
Sorting ASLCheck QC images for spatial CoV:100%
080_SortBySpatialCoV was perform100%
G-zZzZipping 57 files

G-zZzZipping 57 files
Progress:100%
090_DeleteAndZip was performed

Job-iteration 1 stopped at 07-Sep-2020 12:50:40 and took 287 seconds
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++100%
xASL_module_Population completed
```
Bug seems to be fixed. I'll open a pull request.

**Comment by MichaelStritt** [comment]
Closed with recent pull request.
