### ISSUE TITLE
Lesion correction re-run fails

### ISSUE THREAD

**Issue by yevap** [ExploreASL/ExploreASL#1200]
### Description

After the input of registered lesion segmentation in the derivatives folder, deleting the lock folders, and re-running the pipeline, following errors appear and the whole pipeline crashes. 

![image](https://user-images.githubusercontent.com/65025666/194767786-5796cde8-fabe-4089-8138-0a9a902a4f7e.png)

It needs to be corrected to process BTASL data (with ONCOhabitats segmentations)

**HENK** the problem is that the FLAIR is imported incorrectly: as two volumes containing half the brain:

![Image](https://github.com/ExploreASL/ExploreASL/assets/27774254/be958fbb-bd84-4747-a41a-f8898c883d28)

and the T1w is a post-contrast T1w with very poor GM-WM contrast, and the segmentation fails.

![Image](https://github.com/ExploreASL/ExploreASL/assets/27774254/89e66bbc-92eb-4ba0-8ea8-260351e56285)

Also, Lesion_T1_1.nii contains 3 lesions, which should be added individually as Lesion_T1_1.nii Lesion_T1_2.nii etc.

When these things are adapted by Jan, I could try improving the segmentation but for that we might rather wait until we have implemented a new SPM12/CAT12 version.

### How to test

The example dataset for testing lesion correction is available [here](https://cunicz-my.sharepoint.com/:f:/g/personal/29889058_cuni_cz/EiteuUuDsW1KnUwoPbc0XFwBZkYIAotlxkNO43XqeGQK0A?e=Mrs6fR) 

**JAN** This is fine now, this FLAIR is now imported correctly.

### Release notes
Nothing. Was already fixed elsewhere.

**Comment by HenkMutsaerts** [comment]
Looking at this now, sorry for being very late.
1. There are 3 lesions, so I would use them as Lesion_T1_1.nii.gz, Lesion_T1_2.nii.gz, Lesion_T1_3.nii.gz
2. Your FLAIR was incorrectly converted, it had two volumes with each having half a hemisphere, probably something went wrong in the DICOM conversion.
3. 'xASL_adm_GzipAllFiles' went wrong in ExploreASL_Import > xASL_adm_CleanUpX > xASL_adm_GzipAllFiles, trying to zip using the filesystem, because your foldername was 'C:\Users\Heavy Analysis\Documents\BTASL_WIP\tools\ExploreASL\Modules\SubModule_Population\xASL_adm_GzipAllFiles.m', so this requires the usage of " " rather than the \ escaping, and testing this in Windows. This should be fixed be #1302
