### ISSUE TITLE
TotalGM, TotalWM and WholeBrain atlases are the same

### ISSUE THREAD

**Issue by Loowie** [ExploreASL/ExploreASL#1327]
Hi

I'm not sure whether this is an issue or whether I'm doing something wrong, but when computing the mean TotalGM and TotalWM  CBF in the population module this results in the same number for both maps. This seems restricted to NativeSpaceAnalysis only as the numbers in standard space are different between GM and WM.
When checking the maps under External/SPMmodified/MapsAdded the TotalGM, TotalWM and WholeBrain map all look the same and cover the whole brain. When checking the maps for each subject in their ASL map, they are also all the same and cover the whole brain.

How come the StandardSpace ROI analysis seems to be doing OK, but the NativeSpace ROI analysis produces the same results for the totalGM and totalWM maps?

Thanks!

### Release notes
Fix WM maps conversion to native space.

**Comment by jan-petr** [comment]
Hi Loowie,

This definitively sounds like a bug as the StandardSpace and NativeSpace analysis shouldn't differ dramatically. 
Can you please let me know which version of ExploreASL are you using? 
Does it also happen in version 1.10.1 and in the newest 'develop' version?

thanks,
Jan

**Comment by Loowie** [comment]
Hi Jan

I tried this in the ExploreASL-bug-1259_FixNativeSpaceAnalysis developer version of a couple of months ago and i tried it again in version 1.10.1. I'll also upload the TotalGM, TotalWM, DeepWM and WholeBrain .nii maps from external/SPMmodified/MapsAdded. This is from version 1.10.1. TotalGM, TotalWM and WholeBrain all cover the same area.

[WholeBrain.nii.gz](https://github.com/ExploreASL/ExploreASL/files/10871914/WholeBrain.nii.gz)
[DeepWM.nii.gz](https://github.com/ExploreASL/ExploreASL/files/10871915/DeepWM.nii.gz)
[TotalGM.nii.gz](https://github.com/ExploreASL/ExploreASL/files/10871916/TotalGM.nii.gz)
[TotalWM.nii.gz](https://github.com/ExploreASL/ExploreASL/files/10871917/TotalWM.nii.gz)

Thanks
Best

**Comment by HenkMutsaerts** [comment]
Yes, the NativeSpace analysis in the population module was programmed quick and dirty, and we don't use it much. We have an issue to improve the NativeSpace code so these type of bugs will be easier to catch #58, which we may want to prioritize.

ExploreASL's ROI processing in the population module takes an atlas/mask, and multiplies this by a subject-specific GM, WM, deepWM, or whole-brain mask internally. So, this is the reason that these atlases cover the same area, because they signify a wholebrain atlas that needs to be masked by the subject-specific tissue type according to the name of the atlas.

Likewise, if you would take e.g., a vascular territory atlas, and add `WM` to the title, ExploreASL would multiply these by WM instead of the default GM. I thought this was a nice systematic way to process these, but I now see this can also be misleading :)

Note also that all atlases are processed both bilaterally (B), left only (L) and right only (R), so the input atlas should be bilateral.

Hope this helps!

**Comment by Loowie** [comment]
Hi Henk

Ah yes, that makes more sense now. Thanks for the info! So, then it might seem that something goes wrong in taking the subject specific ROI maps and multiplying them by the GM/WM maps?

Best

**Comment by jan-petr** [comment]
It seems that while transfering GM and WM maps from standard to native space, we have taken twice GM maps. So a copy-paste error.

This should be fixed in the branch bug-#1327_nativeSpaceGMWM

**Comment by Loowie** [comment]
Hi

It is now indeed fixed! Thanks a lot!

Best wishes
