### ISSUE TITLE
Conflicts between develop and master

### ISSUE THREAD

**Issue by jan-petr** [ExploreASL/ExploreASL#141]
There are several conflicting edits between master and develop. These have occurred during hotfix 1.2.1 because certain lines fixed there were at the same time improved in the develop and feature branches. So the code in master works, but develop has even a newer version.

These issues should be resolved in release 1.3.0 by accepting the version from the develop branch. Below we list the files and line numbers+line content of the correct version in develop (knowing that the line numbers might change in the future).

**Comment by jan-petr** [comment]
ExploreASL_ImportConfig
Line 850:case 'incoming' % Default single participant

ExploreASL_Initialize
Line 107:if isempty(InitChoice)
Line 146:fprintf('%s\n','Exiting ExploreASL');

ExploreASL_make_standalone
Line 181: '-a', fullfile(ExploreASLPath,'Functions'),...

load2bids:
Line 500:%if ~isfield(importStr{ii}.par,'TotalAcquiredVolumes') && isfield(importStr{ii}.x,'NumberOfAverages') && (importStr{ii}.x.NumberOfAverages > 1)
Line 946: jsonLocal.M0 = [jsonLocal.M0 nnStrOut '_' m0scanStr '.nii.gz'];
Line 1109:if scaleFactor || size(imM0,4) == 1
Line 1127: fullfile(outSesPath,'perf',['sub-' subLabel sesLabelUnd nnStrOut '_' m0scanStr '.nii.gz']));
Line 1144: spm_jsonwrite(fullfile(outSesPath,'perf',['sub-' subLabel sesLabelUnd nnStrOut '_' m0scanStr '.json']),jsonM0Write);

xASL_init_LoadMetadata:
Line 106: MatsDetected = ~isempty(xASL_adm_GetFileList(x.D.ROOT, '^(?!x)(?!xASL)(?!dcm2niiCatchedErrors)).*\.mat$', 'FPList', [0 Inf]));
Line 245:FileList = xASL_adm_GetFileList(x.D.ROOT, '^(?!x)(?!xASL)(?!dcm2niiCatchedErrors)).*\.mat$','FPList', [0 Inf]);
Line 530: %% 4A) Force continuous data for known parameters

xASL_qc_TestExploreASL_HM:
Line 51:[ResultsTable] = xASL_qc_TestExploreASL(TestDirOrig, TestDirDest, RunMethod, 0, MatlabPath, [], [], bOverwrite, [], RunTimePath, 0);

xASL_wrp_RegisterASL:
Line 432: bAffineRegistration = 0;
Line 450:if bAffineRegistration==2 
Line 535: % Write the Tanimoto coefficient to the output QC structure

xASL_wrp_VisualQC_Structural:
Line 93:% Show lesions individually

**Comment by HenkMutsaerts** [comment]
> ExploreASL_ImportConfig
Line 850:case 'incoming' % Default single participant

Michael added this for mTrial's docker

> ExploreASL_Initialize
Line 107:if isempty(InitChoice)
Line 146:fprintf('%s\n','Exiting ExploreASL');

Michael and I added this, such that instead of crashing, if you don't fill anything in the start up GUI dialogue, it will exit nicely

> ExploreASL_make_standalone
Line 181: '-a', fullfile(ExploreASLPath,'Functions'),...

I believe I added this for completion

>  load2bids:
Line 500:%if ~isfield(importStr{ii}.par,'TotalAcquiredVolumes') && isfield(importStr{ii}.x,'NumberOfAverages') && (importStr{ii}.x.NumberOfAverages > 1)
Line 946: jsonLocal.M0 = [jsonLocal.M0 nnStrOut '_' m0scanStr '.nii.gz'];
Line 1109:if scaleFactor || size(imM0,4) == 1
Line 1127: fullfile(outSesPath,'perf',['sub-' subLabel sesLabelUnd nnStrOut '_' m0scanStr '.nii.gz']));
Line 1144: spm_jsonwrite(fullfile(outSesPath,'perf',['sub-' subLabel sesLabelUnd nnStrOut '_' m0scanStr '.json']),jsonM0Write);

Jan edited this

>  xASL_init_LoadMetadata:
Line 106: MatsDetected = ~isempty(xASL_adm_GetFileList(x.D.ROOT, '^(?!x)(?!xASL)(?!dcm2niiCatchedErrors)).*\.mat$', 'FPList', [0 Inf]));
Line 245:FileList = xASL_adm_GetFileList(x.D.ROOT, '^(?!x)(?!xASL)(?!dcm2niiCatchedErrors)).*\.mat$','FPList', [0 Inf]);
Line 530: %% 4A) Force continuous data for known parameters

106 & 245: I've improved this to avoid detecting *.mat that don't contain metadata
530: I've improved this as well

>  xASL_qc_TestExploreASL_HM:
Line 51:[ResultsTable] = xASL_qc_TestExploreASL(TestDirOrig, TestDirDest, RunMethod, 0, MatlabPath, [], [], bOverwrite, [], RunTimePath, 0);

This one I use myself for fast testing, most recent version should be fine (I believe the added 0 is for non compiled)

>  xASL_wrp_RegisterASL:
Line 432: bAffineRegistration = 0;
Line 450:if bAffineRegistration==2 
Line 535: % Write the Tanimoto coefficient to the output QC structure

Jan edited this

>  xASL_wrp_VisualQC_Structural:
Line 93:% Show lesions individually

I probably edited this for improved lesion/ROI visualization

**Comment by HenkMutsaerts** [comment]
![image](https://user-images.githubusercontent.com/27774254/94544412-7c87a800-024b-11eb-93e9-246b7375abdc.png)

Except that instead of cherry-picking the "testing commits", we can also merge them. Note that the "testing commits" should have the prefix o the release.

**Comment by jan-petr** [comment]
Created tempBranch-#1.3.0.

Fixed all the conflicts in 7 commits and it should now all be perfect. Except that 3 files simply cannot be fixed as they are still showing some non-sense conflicts or parts of code that are totally equal. We will have to solve these last three during the merge of tempBranch to the release branch...

**Comment by HenkMutsaerts** [comment]
Saw the issue, similar as with you, couldn't find the difference, this was likely different line endings (as Michael uses Windows I believe). Anyway, simply copy-pasting the file versions from release to tempBranch did the trick, without having to do the "dirty merge". So now you can do the clean merge, after you check you agree with me :)

**Comment by jan-petr** [comment]
This seems to work (CLI merging without conflicts, although WEB-GUI displays it). But essentially fixed and we will see more during the final merging and release. 

I am keeping this open for the reference and for the workflow picture until we do the final merge.

**Comment by jan-petr** [comment]
Conflicts solved when merging the release branch to master.
