### ISSUE TITLE
'NaN' value in qCBF map

### ISSUE THREAD

**Issue by LuuuXG** [ExploreASL/ExploreASL#1417]
### Description

I want to use the qCBF maps created in '..\derivatives\ExploreASL\Population' to further conduct VBM, but they contain 'NaN' value, which does not meet the need of some subsequent VBM processes (eg. standardization of the CBF maps to create z-score map). How to deal with it? I also notice that 'Z-score maps' function is in the plan.

### How to test

In TestDataSet: '..\derivatives\ExploreASL\Population\qCBF_sub-Sub1_1_ASL_1.nii.gz', 'NaN' value can be found in several voxels.

### Release notes

Nothing to release.

**Comment by HenkMutsaerts** [comment]
Dear @LuuuXG,


The masked CBF file has NaNs in areas where one wouldn't want do get ROI averages, e.g., because of vascular artifacts. The non-masked CBF file should not have NaNs inside the brain. There are indeed some NaNs in the image edges, because these were outside the original field-of-view. You can safely set these NaNs to zeros if you want to do voxel-based statistics. The code below should do this for you:

```
ExploreASL; % load ExploreASL
Image = xASL_io_Nifti2Im('pathToYourNiftiFile'); % load your NIfTI file
Image(isnan(Image)) = 0; % set all NaNs to zeros
xASL_io_SaveNifti('pathToYourNiftiFile', 'pathToYourNiftiFile', Image); % save your new NIfTI file
```

PS: note that VBM usually stands for voxel-based morphometry, which implies volumetric changes. For ASL, you could use the term voxel-based analysis (VBA).
