### ISSUE TITLE
Current version does not work for Singularity

### ISSUE THREAD

**Issue by araikes** [ExploreASL/ExploreASL#1437]
### Description

I pulled the current version of the Docker container as a Singularity image for use on our HPC. I'm using the example Docker to run this but cannot on the HPC for obvious reasons. In attempting to convert some data from DICOM to BIDS, I get the following:

```
[adamraikes@gpu56 Allo_test]$ export DATASETROOT=$PWD
[adamraikes@gpu56 Allo_test]$ export IMPORTMODULES=1
[adamraikes@gpu56 Allo_test]$ export PROCESSMODULES=0
[adamraikes@gpu56 Allo_test]$ singularity run -B $PWD:/data/incoming -B $PWD:/data/outgoing $XASL
=============================== Open ExploreASL v1.10.1 Docker ================================
mkdir: cannot create directory '/opt/incoming/': Read-only file system
cp: cannot create directory '/opt/incoming': Read-only file system
Run ExploreASL...
Root directory: /opt/incoming/
------------------------------------------
Setting up environment variables
---
LD_LIBRARY_PATH is .:/opt/mcr/v97//runtime/glnxa64:/opt/mcr/v97//bin/glnxa64:/opt/mcr/v97//sys/os/glnxa64:/opt/mcr/v97//sys/opengl/lib/glnxa64
Unable to obtain exclusive lock on CTF directory because of a file access error. If you are running multiple simultaneous instances of this application, initialization errors may occur.  (To disable this message set the environment variable MCR_INHIBIT_CTF_LOCK.  Additional diagnostic information may be available by setting the environment variables DSERVICES_FSLOCK_VERBOSE and DSERVICES_FSLOCK_WARNING.)
Failed to create a directory required to extract the CTF file.
 Please make sure that you have appropriate permissions and re-run the
 application.
Error initializing CTF Archive: 
Some error has occurred in the file: core/mclCtfFileExtractor.cpp, at line: 62.
 The error message is: 
Failed to create a directory required to extract the CTF file.
 Please make sure that you have appropriate permissions and re-run the
 application.

MCL:ComponentDirectoryExtraction
Error: Error initializing CTF Archive: 
Some error has occurred in the file: core/mclCtfFileExtractor.cpp, at line: 62.
 The error message is: 
Failed to create a directory required to extract the CTF file.
 Please make sure that you have appropriate permissions and re-run the
 application.

cp: cannot stat '/opt/incoming/.': No such file or directory
=========================================== DONE =============================================
```

I am able to convert this same directory using Matlab and the current Github version but that's not a feasible solution for the application I'm looking at: 
`[x] = ExploreASL('/xdisk/adamraikes/testing/Allo_test', 1, 0)`

## Release Notes

Nothing

**Comment by maartenhammer** [comment]
Hi!
This is a duplicate issue of #1177, a workaround for this for now is to remove the `-C` flag in `xASL_dev_MakeStandalone` on line 132 and recompile it for yourself.
We'll get around to testing if this doesn't break anything in the Docker version, if so, we'll release the next version compatible with Singularity. 
It seems to be some issue with how Singularity handles permissions combined with how Matlab MCC generates Archives.

**Comment by maartenhammer** [comment]
Contact with Paul has been made, not as simple as just adding -C flag.

**Comment by HenkMutsaerts** [comment]
@maartenhammer What did you end up doing for this?

**Comment by maartenhammer** [comment]
The issue here is different to the one in #1177 but stems from the same design flaw of the ExploreASL Container. 

The way our Container is set up we do the following: 
1. Mount the container-folder /data/incoming to some folder in the host-system
2. Mount the container-folder /data/outgoing to some folder in the host-system
3. Run the /opt/run.sh script in the container which does:
4. Copy the contents of the /data/incoming folder to /opt/incoming in the container
5. Run ExploreASL on the /opt/incoming/<DATAROOT> 
6. Copt the contents of /opt/incoming to /data/outgoing (linked to the host-system) 
7. End container

For step 4 you need "root" acces in the container. As /opt is a protected file system. 
In docker you run as a "root" by default whereas in other container management software you run unelevated. 
In this case you can fix the problem for singularity by calling the container using the following two options:
``` --fakeroot --writable-tmpfs``` 
`fakeroot` tells the container you have root-like permissions inside the container. 
`writable-tmpfs` makes it so you can write in file system folders insider the container. 
Neither of these options affect the host system (other than your specific mounted folders for input and output) but you do need to enable them. 

We should probably change the location we copy the data to in the following file from /opt/incoming to something like /data/temporary to prevent the issues we have here. 
https://github.com/ExploreASL/Deploy/blob/master/docker/xasl_base/run.sh 

Anyway the latest container (v1.11) can be run by docker, podman and singularity. 
For docker you need no changes in the run command:

``` 
docker run -e DATAROOT=TestDataSet  -e IMPORTMODULES=0 -e PROCESSMODULES=1 -v /home/.../incoming:/data/incoming -v /home/.../outgoing:/data/outgoing xasl:latest 
```

For singularity you need --fakeroot and --writable-tmpfs
```
singularity run --fakeroot --writable-tmpfs --env DATAROOT=TestDataSet --env IMPORTMODULES=0 --env PROCESSMODULES=1 --bind incoming-data/:/data/incoming,outgoing-data/:/data/outgoing  xasl_latest.sif 
```

For podman it depends if your host uses SELinux, in which case you either need --privileged:
```
podman run -e DATAROOT=TestDataSet --privileged -v /home/mshammer/my-scratch/incoming-data:/data/incoming -v /home/mshammer/my-scratch/outgoing-data:/data/outgoing xasl:latest
```
Or you should mount the incoming/outgoing folders differently:
```
podman run -e DATAROOT=TestDataSet --mount type=bind,source=/home/mshammer/my-scratch/incoming-data,target=/data/incoming,Z --mount type=bind,source=/home/mshammer/my-scratch/outgoing-data,target=/data/outgoing,Z xasl:latest
```

**Comment by maartenhammer** [comment]
Discussion with Jan Petr
- [x] Change location of Data copy (run.sh) from /opt/ to /data/temporary
- [x] See if this fixes problem with singularity.
- [x] Update Manual

**Comment by maartenhammer** [comment]
Issue: Google drive stops the download of the latest.zip with a page "this file is too big for virusscanner, download anyway?" and our wget in Deploy doesn't work anymore. 

https://stackoverflow.com/questions/37453841/download-a-file-from-google-drive-using-wget/75790977#75790977 
Doesn't work either.

**Comment by maartenhammer** [comment]
Temporarily hosting the Repository somewhere else, changes from /opt/ to /data/temp seems to work within singularity, removing the need for --fakeroot (but still --writable-tmpfs) and podman (no changes), discussion with jan about implementation soon.

With these changes you can run this command on the exploreasl xasl-beta:latest version on our beta release of dockerhub. (which is currently based on the v1.11 release of Exploreasl.)

```
singularity run --writable-tmpfs --env DATAROOT=TestDataSet --env IMPORTMODULES=0 --env PROCESSMODULES=1 --bind incoming-data/:/data/incoming,outgoing-data/:/data/outgoing  xasl-beta_latest.sif
 ```

**Comment by maartenhammer** [comment]
Discussion with Jan & Henk Jan:
Move ExploreASL compiled versions to github from Google & create a public repository for it.
Edit: github does not allow files larger than 100MiB, we could add the compiled versions in the [releases](https://github.com/ExploreASL/ExploreASL/releases/tag/v1.11.0) section though. file limit there is 2Gib.

**Comment by maartenhammer** [comment]
Updated Github Documentions to include the commands for Podman and singularity, created new Issue to adress the Google drive issues #1714 

Release notes:
Changed container to no longer copy data to the temporary file system, introducint fakeroot issues in singularity.
