### ISSUE TITLE
New FSL version that incorporates Amnah's FABBER/DEBBIE processing code

### ISSUE THREAD

**Issue by jan-petr** [ExploreASL/ExploreASL#1461]
### Description

In order to process our data, we need to concatenate two PWIs before quantification: the first PWI.nii includes 14 PLDs and single TEs, followed by another PWI.nii with 3 PLDs but 8TEs per PLD, a total of 14 + 3x8 = 38 volumes. We concatenate the two niftis and input this final nifti to Fabber. To do that, we were using a recompiled version of Fabber (FSL version 6.0.4) with Amnah Mahroo's new model files.

This is how our FSL.txt file (Fabber command) looks like:
[FSL_ModelOptions.txt](https://github.com/ExploreASL/ExploreASL/files/12280794/FSL_ModelOptions.txt)

...which matches a nifti including the two PWIs merged. This 'nte' option defined how many TEs each PLD has, which is critical in our data.

Recently, we noticed that a new version of FSL was released, which incorporates Amnah Mahroo's code for the multi-te extended model, including ITT fitting. However, this version does not support the 'nte' option. This latest version always expects a nifti with TI x TE number of volumes and does not read the option 'nte'. Below you can find some of the errors created when using the newest FSL version and the above-mentioned .txt file

### UPDATE

FSL version 6.0.7 has all errors fixed and works with Hadamard-multi-TE without extra code, compilation etc with ExploreASL under the normal version. So no updated are needed except for stating this in the documentation:

- [x] Explain in the documentation how to set a path to FSL that is not usual.
- [x] Explain that DEBBIE works with FSL 6.0.7 out of the box.

### Release note
Nothing. The issue worked out of the box.

**Comment by BeatrizPadrela** [comment]
Since Mervin was not able to run the compiled FSL version in his Mac, he downloaded the most updated FSL version, which already has Amnah's fabber_asl files (Mervin and I checked this together, the files match line by line).

However, when running Fabber with our FSL_ModelOptions.txt (which has all TIs and TEs and NTEs etc), this error appears:

![image](https://github.com/ExploreASL/ExploreASL/assets/73699072/18ac82b6-6ae0-44f9-8eea-b9f5e122eb75)

**Comment by BeatrizPadrela** [comment]
Mervin was not able to run the compiled FSL on his Mac, so he downloaded the latest FSL version (6.0.6), and checked that the fabber_asl files were the same as Amnah's, and the code also had her name, so the new FSL version has already Amnah's code implemented.

So he tried to run Fabber with the most recent FSL version and this is the error he encountered:

![image](https://github.com/ExploreASL/ExploreASL/assets/73699072/ccc56f95-cd72-4134-a10f-507673596dad)

**Comment by BeatrizPadrela** [comment]
Then, Mervin and I wanted to understand the meaning of that 646 value, which is actually 38*17, and 17 is the number of TI, NTE, and tau values we have in the FSL_ModelOptions.txt file.

So, we tried some experiments, and with this new FSL version, we cannot use Fabber with the concatenated images. Because it doesn't take into account the --nte (nr of TEs) command, so it always multiplies the te x ti

![image](https://github.com/ExploreASL/ExploreASL/assets/73699072/d329f90f-4755-4d28-92ab-ab0355eac6b6)

in this case, it multiplies 22 x 17 = 374 (see error dimensions)

**Comment by BeatrizPadrela** [comment]
however, if we quantify HAD4 separately, as you can see here (this txt works), it just multiplies the ti x te = 3 x 8, so it runs correctly (see below)

so, our conclusion: this new Fabber/FSL version does not allow us to use one single txt for the concatenated HAD8+HAD4, as we have multi-pld/singleTe + singlePLD+multiTE in the same nifti

![image](https://github.com/ExploreASL/ExploreASL/assets/73699072/6ca4a544-b7d2-4f11-9505-a2cba3d60b79)

**Comment by BeatrizPadrela** [comment]
We just know that in Mac, the new version does not work with out .txt files

Mervin couldn't test our compiled version in his mac

**but now we'll test the new version in flux**
