### ISSUE TITLE
Anonymization 50 flavors (DICOM)

### ISSUE THREAD

**Issue by HenkMutsaerts** [ExploreASL/ExploreASL#178]
Remaining issues:
- Folder name should be: [Manufacturer '_' ArterialSpinLabelingType '_' MRAcquisitionType '_' PulseSequenceType '_' BSupY '_' SoftwareVersions '_' Run]
- Remove all we can from studyPar.json

Done for:
- All GE
- Part Philips

### Release notes
Anonymization and cleaning of Flavors database (should we report this to ExploreASL code or not?!)

**Comment by jan-petr** [comment]
Folder names were anonymized. Files names were anonymized. DataPars were anonymized.

Now we only need to check all the DICOM files for the presence of studynames, site names etc.

**Comment by jan-petr** [comment]
Where do we put those once we are ready? They can't be public - on the same place as the testdata? Note that this is 2GB of small dicom files...

**Comment by HenkMutsaerts** [comment]
A private Github should be fine right? Inside the ExploreASL organization

**Comment by jan-petr** [comment]
Yes. Private is fine. Once I am done with all the DICOM file anonymization and add all the json files, I'll start uploading so that the first version is already clean.

**Comment by HenkMutsaerts** [comment]
It's here: https://github.com/ExploreASL/FlavorDatabase, private and well, so you can upload it, and let's close this one then

**Comment by jan-petr** [comment]
@HenkMutsaerts 45 now - with 2 ADNI ones from Michael. All neatly uploaded. Check how you like it - and you can try the unit testing scripts - see changes.md

**Comment by HenkMutsaerts** [comment]
Looks good! 


### For the BIDS parts, I would:
* move the parameters that are also in the `*_asl.json` sidecar, out of the `studyPar.json`
* `imPar.json`: perhaps rename to `sourceStructure.json` for clarity
* Check that the `sourceStructure.json` is valid, e.g. for Siemens_PCASL_volunteer it is invalid (DICOM folders have a different name than specified in folderHierarchy?)
* Anonymization is incomplete, e.g. studyPar.json still includes "HowToAcknowledge" or the DICOM filenames have not been anonymized (at least for Siemens_PCASL_volunteer, but this should be checked in the scripts for all)
* Also for foldernames: I would replace "volunteer/glioma/GBM/AD" by their sequence difference, e.g. "Bsup/WIP" etc
* `PulseSequenceType`: is this updated to new ASL-BIDS (i.e. now this allows free text, other than 2d_epi/3d_grase/3d_spiral)?
* PulseSequenceDetails: is this supposed to be a concatenation of [ManufacturersModelName SoftwareVersions] ?
* `"BackgroundSuppressionPulseTime":[1.68,2.83]` -> does this work in JSON/BIDS/Matlab? Or should this be:
`"BackgroundSuppressionPulseTime":"[1.68,2.83]"` ?
* Every field with "Random Description" should probably be removed? Either we have information or we don't :)
* Do we keep the "non-informative" fields, e.g. "ReceiveCoilName":"MULTI_COIL", or "ScanOptions":"FS" ?
* Also, these "non-informative fields" are heterogeneous, e.g. Siemens includes "ReceiveCoilActiveElements":"C:HEA;HEP" which Philips doesn't. Not sure if this amounts to standardization ;)
* When I download and open `https://github.com/ExploreASL/FlavorDatabase/blob/main/Philips_PCASL_3DGRASE_R5.4_TopUp/rawdata/sub-Sub1/perf/sub-Sub1_asl.nii.gz`, mricron gives me the warning "the Header file is not in NIfTI format (the first 4 bytes do not have the value 348). Assuming big-endian data. And then the values are unreadable, same for the orientation matrix (though it is able to show the image matrix). I would at least test that all the nii.gz can be opened with something like mricron (is fastest to try in any OS).

* All these examples went through the validator right? Does this "unit test" script convert them all in batch from dcm2bids and then all test them with the validator (maybe we don't need this)?

### Minor
* if you say "zipped a few files" I have to search which files; it helps to be specific (e.g. "zipped all .nii to .nii.gz")

**Comment by jan-petr** [comment]
See inline comments (the rest I agree with and is done). Let me know which ones you don't agree with.

> * All these examples went through the validator right? Does this "unit test" script convert them all in batch from dcm2bids and then all test them with the validator (maybe we don't need this)?

Yes. CustomScripts/StudySpecificScripts/BIDS/BIDSFlavorsTest.m converts them all in a batch and compares with the reference import. The reference import was tested by validator and checked by me and Patricia.

> * move the parameters that are also in the `*_asl.json` sidecar, out of the `studyPar.json`

Yes - needs some more work - part of issue 232.

> * Check that the `sourceStructure.json` is valid, e.g. for Siemens_PCASL_volunteer it is invalid (DICOM folders have a different name than specified in folderHierarchy?)

It is valid for all - all the flavors were tested multiple times. For that dataset - there were some extra copy-pasted directories that were not necessary, which are now deleted, but it worked nevertheless.

> * Anonymization is incomplete, e.g. studyPar.json still includes "HowToAcknowledge" or the DICOM filenames have not been anonymized (at least for Siemens_PCASL_volunteer, but this should be checked in the scripts for all)

The studies were anonymized, so I have put in some dummy text and variables to keep it filled with something. That PMID article doesn't exist. All DICOMs were anonymized, all flenames were anonymized. None of the study-description things are real.

> * Also for foldernames: I would replace "volunteer/glioma/GBM/AD" by their sequence difference, e.g. "Bsup/WIP" etc

We can do that if you really want, but I wanted to keep the disease relevance after anonymization just in case it is useful in th future.

> * `PulseSequenceType`: is this updated to new ASL-BIDS (i.e. now this allows free text, other than 2d_epi/3d_grase/3d_spiral)?

Yes - updated sort of - we put the basic text as below as nothing else can be extracted from DICOMs anyway :) Fine?

> * PulseSequenceDetails: is this supposed to be a concatenation of [ManufacturersModelName SoftwareVersions] ?

No, it is supposed to contain pulse sequence details, so this concatenation is there just for now - can be replaced with something better in the future.

> * `"BackgroundSuppressionPulseTime":[1.68,2.83]` -> does this work in JSON/BIDS/Matlab? Or should this be:
>   `"BackgroundSuppressionPulseTime":"[1.68,2.83]"` ?

Yes - this works. A numeric array - that's what we want. Your suggestion would be a string.

> * Every field with "Random Description" should probably be removed? Either we have information or we don't :)

It's anonymized dataset, we can't put the real description. So we have used a dummy text. It's not hard-coded in the code, but rather converted from the studyPar.json. So no problem having it - for testing.

> * Do we keep the "non-informative" fields, e.g. "ReceiveCoilName":"MULTI_COIL", or "ScanOptions":"FS" ?

These are from DICOMs directly and part of general BIDS. I would keep all those that are in BIDS, because they are potentially useful for other reasons and we don't want to use any difficult decision making process to sort them.
But you are right, that BIDS probably requires that these fields are standardized, not just taken from DICOM. I can check the BIDS definition and keep only the fields that are supposed to be direct DICOM copy.

> * Also, these "non-informative fields" are heterogeneous, e.g. Siemens includes "ReceiveCoilActiveElements":"C:HEA;HEP" which Philips doesn't. Not sure if this amounts to standardization ;)

Same as above - I was blindly copying other fileds from BIDS just because they were in BIDS.

> * When I download and open `https://github.com/ExploreASL/FlavorDatabase/blob/main/Philips_PCASL_3DGRASE_R5.4_TopUp/rawdata/sub-Sub1/perf/sub-Sub1_asl.nii.gz`, mricron gives me the warning "the Header file is not in NIfTI format (the first 4 bytes do not have the value 348). Assuming big-endian data. And then the values are unreadable, same for the orientation matrix (though it is able to show the image matrix). I would at least test that all the nii.gz can be opened with something like mricron (is fastest to try in any OS).

All was normally saved with dcn2nii or with the standard xASL functions. Is this the case with other datasets as well. I can normally open it with MITK...

**Comment by HenkMutsaerts** [comment]
* Every folder name has the same combination/concatenation of BIDS fields: 
[Manufacturer '_' ArterialSpinLabelingType '_' MRAcquisitionType '_' PulseSequenceType '_' SoftwareVersions]
Jan will adapt this, and if needed, adapt the JSON fields accordingly.

* Rename studyPar.json to conversionPar.json
* All dummy fields (e.g. "RandomInfo" or "PMID" should include "dummy" e.g. "DummyRandomInfo" or "www.zsguhzsgDummyArticle.org"

**Comment by MichaelStritt** [comment]
@HenkMutsaerts: @jan-petr just did a really nice revamp of the flavors. We can probably close this issue.

**Comment by jan-petr** [comment]
@MichaelStritt - yes, we can just close this, but I had to commit to ExploreASL as well to change some names in the testing script. I simple approval + merge is needed :)
