### ISSUE TITLE
xASL_stat_StdNan & xASL_stat_MadNan rounding errors

### ISSUE THREAD

**Issue by HenkMutsaerts** [ExploreASL/ExploreASL#1830]
### Description

There is something going wrong in our NaN calculations for differences from the mean (SD and MAD). If you run the following code, you will see that the answer from the dimension choice vs for-loop are not identical whereas they should be?

```
randomValues = randn([3600*17, 30]);

SD1 = xASL_stat_StdNan(randomValues, [], 1);

for iRepetition=1:size(randomValues,2)
    SD2(iRepetition) = xASL_stat_StdNan(randomValues(:,iRepetition));
end

isequal(SD1, SD2)

MAD1 = xASL_stat_MadNan(randomValues, [], 1);

for iRepetition=1:size(randomValues,2)
    MAD2(iRepetition) = xASL_stat_MadNan(randomValues(:,iRepetition));
end

isequal(MAD1, MAD2)
```

### Release notes

Nothing - problem is in Matlab internal built-in function sum that generate different results.

**Comment by jan-petr** [comment]
The problem is in Matlab internat command SUM

MEN1 = sum(randomValues, 1);

for iRepetition=1:size(randomValues,2)
    MEN2(iRepetition) = sum(randomValues(:,iRepetition),1);
end

isequal(MEN1, MEN2)
MEN1-MEN2

Shows that this makes a different. Really no clue where the problem is and how to solve this. But an inherent Matlab problem. Not clear which is the correct solution to use.
