### ISSUE TITLE
Cluster Preparation for Unit Testing

### ISSUE THREAD

**Issue by MichaelStritt** [ExploreASL/ExploreASL#204]

**Comment by MichaelStritt** [comment]
### Security issues from dependabot

- Bump twisted from 18.9.0 to 20.3.0
- Bump httplib2 from 0.14.0 to 0.18.0
- Bump httplib2 from 0.14.0 to 0.18.0

**Comment by jozsait** [comment]
@MichaelStritt, I think this security issue is resolved. Requirements have been updated as suggested by dependabot.
First I pushed without registering my email address, this is shown as unverified. For this reasons the first two commits have been deleted so that only the last, verified commit shows up in the history of the repository.

**Comment by jozsait** [comment]
@MichaelStritt, I think the security issue is resolved. Requirements have been updated as suggested by dependabot.
First I pushed without registering my email address, this is shown as unverified. For this reasons the first two commits have been deleted so that only the last, verified commit shows up in the history of the repository.
I haveclosed this issue but then I have realised that it should be used as long as Cluster Preparation #204 is under development as described on the wiki.

**Comment by MichaelStritt** [comment]
Hey @jozsait, great work!
I've recently done a few commits from a local repository without a key, too. It's pretty easy to [sign them afterwards](https://github.com/ExploreASL/ExploreASL/wiki/To-sign-existing-Commits), if it hasn't been too long ago. But you're free to do this however you like. 
Regarding the opening and closing of the issue: we don't have a hard rule here. The only thing we stopped doing are continuous issues, which are open for more than a few months (or forever). We had some for "minor bugs" for example, but those got really messy after a while. After each release we mention some of the finished issues of the "closed" list. To cut a **long story short**, most of the time we close issues after merging the branch. And again, great job and thanks for all the coding 👍

**Comment by HenkMutsaerts** [comment]
+1 from me! Though we do usually have some explanation on what an issue is about, @MichaelStritt "Cluster Preparation" was initially a bit vague to me, am I being tested? ;)

**Comment by MichaelStritt** [comment]
You're not being tested, at least not by me ;)
I just don't want Tamas to think that we're 100% strict with some of the rules 👍

**Comment by MichaelStritt** [comment]
Hey @jozsait,
I know you've probably been busy with ISMRM and christmas stuff, too. I just wanted to ask if this is ready to be merged for release 1.4.0 or do you want to add any additional code? Since all of it (I think) is in Development, we probably don't have to extensively test this right now.
