### ISSUE TITLE
Phoenix Protocol Reader

### ISSUE THREAD

**Issue by MichaelStritt** [ExploreASL/ExploreASL#223]
- Implementation of a function to read and a function to analyze the Siemens phoenix protocol (private tag 0x29,0x1020)

**Comment by HenkMutsaerts** [comment]
@MichaelStritt can you please provide a description to this issue ;)

Also, we should probably have a similar issue for reading the Philips XX files (when Sandeep is ready with this)

**Comment by jan-petr** [comment]
Yes, issue 194 lists all these advanced BIDS import options (including Philips XX), we have isolated the Phoenix thing because we can easily do it already...

**Comment by MichaelStritt** [comment]
Hey @jan-petr, I added the option for DCMTK here 1d8050a but can you show me the code snipped how to do this?

**Comment by MichaelStritt** [comment]
- Issue: There are two parameters which include the word **lrepetitions** in 3D GRASE PCASL datasets
    - Possible solution: Search parameter list only for exactly matching parameters instead of using include
- We could still improve the logic for the interpretation of the **parameters** regarding the **xasl** struct

**Comment by jan-petr** [comment]
Copying my review also here (as we have agree previously to have all copied also in the issue branch):

Looks very good. Some minor changes to do:

- Explain in the header what is the alternative to bUseDCMTK - i.e. Python
- Why is the phoenixProtocol output a cell and not a string?
- I already perform the reading of the Phoenix in my import. It would be thus good to split the reading itself and the parsing of the protocol to two independent functions. I mean that you can read+parse in a single function, but I need the parsing also separately.
- Please be more verbose in the description of the function so that the inputs/outputs/function is more clear.

Smart to have the ASL and 'raw parameter' output - I guess there's still a plenty of work ahead of us.

**Comment by jan-petr** [comment]
Copying the answer from Michael also here (sorry, my fault not starting the discussion here):

Hey @jan-petr, I tried to fix as much as possible in e27e33e.

> Explain in the header what is the alternative to bUseDCMTK - i.e. Python

> Please be more verbose in the description of the function so that the inputs/outputs/function is more clear.

The header description should be a bit better now.

> Why is the phoenixProtocol output a cell and not a string?

In Matlab I personally find it easier to work with cell arrays. I added a separate raw output now 👍 

> I already perform the reading of the Phoenix in my import. It would be thus good to split the reading itself and the parsing of the protocol to two independent functions. I mean that you can read+parse in a single function, but I need the parsing also separately.

Are you thinking of a separate script or just a separate function? I implemented a separate function, but I'd be happy to change it if you were thinking of something else.

> Smart to have the ASL and 'raw parameter' output - I guess there's still a plenty of work ahead of us.

I had a meeting with a colleague from Bremen a few minutes ago. He's developing ASL sequences with Matthias. I showed him some of the parameters and it seems that you have to be an expert in actual sequence development for some of it. He said we should be careful with the sWipMemBlocktFree parameter e.g., since this can be defined manually at the scanner. He also talked about how you can "see" the actual sequence in some of those alTI[x] parameters. What shocked me the most was when we talked about the tSequenceFileName. Currently we get most of the information from there and he said that this is correct for most of the cases, but you could still run a different sequence and still store false protocol information there.

**Comment by jan-petr** [comment]
Thanks for the fixes @MichaelStritt ! Looks very good. Some minor stuff:

- "The file extension should be either ".dcm" or ".IMA"" - Unfortunately, there are sometimes DICOM files without any extension as well.
- Thanks for improving the header. It looks good and it will hopefully save us work in the future ;)
- Sorry - I meant a separate standalone script in a separate file. So that I can parse the raw-Phoenix I have extracted from DICOM previously and get the ASL values without reading the DICOM again. The separate function within this file is good as well, as it will make stuff easier to read, but not really what I meant.
- Nice to talk with the sequence guy! Any rules we can actually use? Interpretation of alTI[x] would be really helpful - we can for sure find the PASL Q2TIPS from there and some multi-PLD etc. 
- The SequenceNames in DICOM are notoriously unreliable, MR technicians like to change it occasionally to the name of their dog etc (just jokin). For big multi-center studies, only the actual parameters (TE, TR etc) and the image itself are reliable sources of information. Scary though that this applies for tSequenceFileName as well :D

Do you want to add some of the functionality from the Bremen guy there before the merge? Who was he BTW?

**Comment by MichaelStritt** [comment]
Hey @jan-petr, thanks for the feedback 👍 

> "The file extension should be either ".dcm" or ".IMA"" - Unfortunately, there are sometimes DICOM files without any extension as well.

Okay, I turned the warning into a console output.

> Sorry - I meant a separate standalone script in a separate file. So that I can parse the raw-Phoenix I have extracted from DICOM previously and get the ASL values without reading the DICOM again. The separate function within this file is good as well, as it will make stuff easier to read, but not really what I meant.

Oh, no worries, this way I can make it even more modular. Check out e440af5. To run all at once you can use...
`[xasl,parameters,parameterList,phoenixProtocol] = xASL_bids_GetPhoenixProtocol(pathData,bUseDCMTK)`
...and for reading the raw protocol only we can use...
`[parameterList,phoenixProtocol] = xASL_bids_PhoenixProtocolReader(rawPhoenixProtocol)`
...the interpretation is done by the analyze function...
`[xasl,parameters] = xASL_bids_PhoenixProtocolAnalyzer(parameterList)`

I tested it for two ADNI datasets this morning, but I switched around a lot of code, so if there's an error somewhere please let me know and I'll fix it as fast as possible :)

> Nice to talk with the sequence guy! Any rules we can actually use? Interpretation of alTI[x] would be really helpful - we can for sure find the PASL Q2TIPS from there and some multi-PLD etc.

I don't know if you know Simon already? I think he's going to be part of ASPIRE too, but I'm not sure. We didn't write down actual rules. I think rules based on the alTI[x] could possibly be quite complex and a lot of manual work for him/us. But maybe we can arrange a meeting and discuss some stuff together :)
