### ISSUE TITLE
Super Gzip/Gunzip for Windows

### ISSUE THREAD

**Issue by MauricePasternak** [ExploreASL/ExploreASL#262]
I find the gzip step in the Population Module to be a considerable time bottleneck ,especially on Windows. The fault being base MATLAB's lack of multi-threading capability to queue the next I/O operation such as compressing or decompressing files. Therefore, I'm opting to create a one-file executable that will operate out of the command line to gunzip or gzip in a multithreaded manner.

Signature is as follows:

    SuperGzip root_dirs glob_pat [--decompress] [--keep_orig] [--recursive] [--n_threads] [--pause]

root_dirs is either a single path or a wildcard path string interpreted as a list of paths. These are roots from which globbing will take place. This is useful if one wishes to only compress/decompress certain directories but not others. But the typical use case is probably to just specify the root study folder.

glob_pat is the glob pattern to use when searching for files to compress/decompress

--decompress is whether to decompress from .gz (True) or compress to .gz (False; default)

--keep_orig is whether to keep the original file that was compressed or decompressed. Default is to not keep original files.

--recursive is whether to have the globbing act recursively from the indicated root directory or not. Recursive behavior is on by default.

--n_threads is the number of threads to call. Defaults to 4. Calling too many threads is detrimental.

--pause allows for the executable to print a summary of the arguments entered and has the user enter a y/n while loop to confirm the operation. By default this is off, as the assumption is that the executable will be called non-interactively by a program.

-h is the typical help summary of the executable and its arguments

My questions:

- What is the suggested location to store the executable before making this a pull request?

- Should any changes to xASL_adm_GzipAllFiles be included as part of the pull request?

**Comment by MauricePasternak** [comment]
Just did a quick speed test on Windows on only 8 subjects (~344 .nii files to gzip). Even at this small number and the overhead associated with calling the executable, it accomplishes the gzipping in 50 seconds in constrast to the MATLAB implementation taking 1 min 20 seconds. I can imagine the gains starting to look even more significant at higher subject counts.

**Comment by MichaelStritt** [comment]
> I'm opting to create a one-file executable that will operate out of the command line to gunzip or gzip in a multithreaded manner.

Sounds great! Are you talking about a **.exe** or a tool within **WSL**? 

> What is the suggested location to store the executable before making this a pull request?

I'm not 100% sure I understand the problem. I'd just create a feature branch and put the file/script into the Development folder (if you can wait a day or two, then I'd wait with the branching until we properly released v1.4.0). Later it can become a part of Functions. Maybe @jan-petr can add to this, if there's another common practice in xASL 👍 

> Should any changes to xASL_adm_GzipAllFiles be included as part of the pull request?

I guess for testing you probably need the option to run your executable within xASL_adm_GzipAllFiles, so I'd just modify xASL_adm_GzipAllFiles within the feature branch and then we'll review if all the changes you made were okay 👍

**Comment by HenkMutsaerts** [comment]
Yes, this is a good idea. I noted this before and already implemented that for Linux it uses the system gzip rather than Matlab's gzip; though this had a different reason: Matlab's gzip is dependent on jvm (one of the very few parts of ExploreASL), though with Windows this is probably not really an issue. The Linux gzip is also faster than Matlab's gzip but probably because of the faster file-handling than multi-threading (I am not sure Linux gzip does multithreading by default). 

Also, multi-threading can be done with Matlab using `parfor`, but this requires a separate toolbox, which we aim to avoid in ExploreASL, as this is not always present.

Per your questions, and Michael's: is `superzip` a separate Windows executable? Everything that is not part of ExploreASL (essentially that has a different license), should be in a subfolder in `/External`. The number of threads should be chosen automatically, by first querying the number of processing units available. All this should be a Windows-only part inside `xASL_adm_GzipNifti` and `xASL_adm_UnzipNifti`, and `xASL_adm_GzipAllFiles`, these functions mainly deal with the potential for both `.nii` and `.nii.gz` without the user needing to deal with this (i.e. checking if both are present, deleting if they are identical, or throwing a warning, and loading a different extension if needed).

And indeed, of course, you should follow our Github workflow, so make a branch that refers to this issue and fix stuff inside this branch, we can then also check your commits to this branch even before you make it into a PR if you want.

**Comment by MauricePasternak** [comment]
Yes, it is a separate executable under Windows. As per request, I stored it in `External`. A call is made to it in `xASL_adm_GzipAllFiles` for the time being under the conditions of `bUseLinux` is False. 

It will launch a number of threads equal to either the number of processing units avaliable or the number of files detected by `xASL_adm_GetFileList`, whichever one is the smaller of the two, to avoid spawning orphaned threads.

I'm not sure about putting it in the other 2 functions. This executable was made with the assumption that it will be provided a globbing character like `*.nii` and operate on many, many files, thereby justifying the overhead since the speedup of multithreading will catch up quickly. Not good for use on single files like the other two functions seem to be designed for.

It's not a pull request yet, but I invite you and @MichaelStritt to give it a shot.

**Comment by MichaelStritt** [comment]
@MauricePasternak: Tested it. Works really well and seems quite fast. Another great open source tool 👍 

![SuperGzip1](https://user-images.githubusercontent.com/46593074/106583329-446bdb00-6545-11eb-8540-9c945ea0a818.PNG)

![SuperGzip2](https://user-images.githubusercontent.com/46593074/106583342-47ff6200-6545-11eb-8088-9b9d82a5a6b3.PNG)

**Comment by MichaelStritt** [comment]
**Note to myself:**

If we use `if ispc` and something like...
```
try
    status = system('SuperGZip_Windows.exe root_dirs "..." pattern ...')
catch
    use alternative
end
```
... then we could integrate this in the final zipping at the end of the ExploreASL pipeline, right?

I could do some tests to check the performance increase on windows.

**Comment by MauricePasternak** [comment]
Note: the default number of threads called is 4 (no one has a Duo Core anymore these days), but for more formidable workstations, you may want to change that argument to something higher or benchmark to see if that even makes a difference (i.e. diminishing returns).

**Comment by HenkMutsaerts** [comment]
> Note: the default number of threads called is 4 (no one has a Duo Core anymore these days), but for more formidable workstations, you may want to change that argument to something higher or benchmark to see if that even makes a difference (i.e. diminishing returns).

Mind that single-threading should always be possible, there are still certain server architectures that parallelize by many single-core instances.

**Comment by HenkMutsaerts** [comment]
@MauricePasternak and @MichaelStritt Looks good guys! Few comments:

* Why do you add a new option as second argument rather than on the end, not to confuse the current operations? Good practice is always to add new options at the end. Minor spelling check it should be "path to ..." not "path to THE ..."

* `system` has two outputs, one is the exit code and one the message. It helps to print the message if it doesn't exit cleanly.

* You could use the x-table that includes the ExploreASL path, but otherwise you could call it `MyPath`. `x.MyPath` is how the ExploreASL path is called. And you add the "External" folder to the path. That is clearer than the current explanation.
* You can consider adding an `if ispc` statement before doing all the `getenv` etc, just to ensure that this doesn't bother your common use in Linux (which is the OS that we will use mostly with the GUI, docker, etc in the future).

>> getenv('NUMBER_OF_PROCESSORS')

ans =

  0×0 empty char array

This doesn't seem to work on macOS (so probably also not on Linux), but this could be a version issue.

>> feature('numcores')
MATLAB detected: 8 physical cores.
MATLAB detected: 16 logical cores.
MATLAB was assigned: 16 logical cores by the OS.
MATLAB is using: 8 logical cores.
MATLAB is not using all logical cores because hyper-threading is enabled.

ans =

     8

This seems to work! So I would use that.

* Are you sure you are running SuperGzip recursively? And is it zipping each file individually (rather than creating one big file)?

* I would keep the default looping script, in the case that `superzip/ispc` and `isunix/git` fail (the rare case that superzip crashes, or git is not installed in whatever unix system).

**Comment by MichaelStritt** [comment]
> @MauricePasternak and @MichaelStritt Looks good guys! Few comments:

99.9% Maurice's work 👍 

> * `system` has two outputs, one is the exit code and one the message. It helps to print the message if it doesn't exit cleanly.

Sure, sounds good.

> * You could use the x-table that includes the ExploreASL path, but otherwise you could call it `MyPath`. `x.MyPath` is how the ExploreASL path is called. And you add the "External" folder to the path. That is clearer than the current explanation.

Are you talking about the added line in `ExploreASL_Initialize.m` ? I think that's quite useful, especially if we add other tools in the future. We could even improve the lines above with the path definition of the External folder. But sure, we can also just use `xASL_adm_GzipAllFiles(x.D.ROOT, fullfile(x.MyPath,'External'));` in `xASL_module_Population.m`. Just a style-wise decision, I think.

> * You can consider adding an `if ispc` statement before doing all the `getenv` etc, just to ensure that this doesn't bother your common use in Linux (which is the OS that we will use mostly with the GUI, docker, etc in the future).

Isn't using `ispc` redundant? There's already the `bUseLinux` statement which takes care of that.

> feature('numcores')
> This seems to work! So I would use that.

Seems good. I'll test that.

> * Are you sure you are running SuperGzip recursively? And is it zipping each file individually (rather than creating one big file)?

Worked for me when testing it with the TestDataSet.

> * I would keep the default looping script, in the case that `superzip/ispc` and `isunix/git` fail (the rare case that superzip crashes, or git is not installed in whatever unix system).

Sure, we can use if `exit_code == 1` to check if the previous part failed. Then we use the slow method instead, right?

**Comment by HenkMutsaerts** [comment]
> Sure, we can use if exit_code == 1 to check if the previous part failed. Then we use the slow method instead, right?

Yes!
