### ISSUE TITLE
Default option xASL_adm_GzipNifti

### ISSUE THREAD

**Issue by MichaelStritt** [ExploreASL/ExploreASL#273]
Hey, only a minor issue. In the header it says, that the default for bOverwrite is **false**, but it seems like it's **true**.
pathOut = xASL_adm_GzipNifti(pathIn, bOverwrite)

```
bOverwrite - indicates if we should overwrite the .NII file (OPTIONAL, default = FALSE)
```
...
```
% Check for the optional parameter overwrite
if nargin < 2 || isempty(bOverwrite)
    bOverwrite = 1;
end
```

**Comment by jan-petr** [comment]
Good catch. Except that I would change the description and keep the functionality. Rather than the other way around. Mainly because we had plenty of issue with files not correctly overwriting etc. And these things were creating a lot of trouble when pausing and re-running pipelines. So it is likely that we had to change the default and forgot to change the header as well. So better to keep it as it was and change the header.
