### ISSUE TITLE
Calculation background suppression efficiency for pseudo-M0

### ISSUE THREAD

**Issue by HenkMutsaerts** [ExploreASL/ExploreASL#35]
When no M0 is obtained, and the control image needs to be used as pseudo-M0, the suppression efficiency needs to be calculated. For 2D EPI this is slice-wise. When the option "UseControlAsM0" is selected, and background suppression is on, then this parameter - that should be a vector for 2D multislice - should be checked and applied when the pseudo-M0 is created.

**Comment by HenkMutsaerts** [comment]
## General
* In practice, only some earlier Siemens 3D GRASE and Philips 2D EPI sequences have background suppression but miss a separate M0 image;
* For both: we set "M0" : "UseControlAsM0", which will create a "pseudo-M0" from the (mean) control image (of course throwing an error if this doesn't exist, we need the raw control-label intermediate images to do this correction);
For 3D: compute a single correction value and apply this to the "pseudo-M0"
For 2D: compute a slice-wise correction value (i.e. adding the SliceReadoutTime iteratively) and apply these to the "pseudo-M0" slices

## For Philips 2D EPI
Usually 2 background suppression pulses are played, that are specified in the examcard/protocol text file. From these it should be easy to compute its effect, but we need to compute this for each slice.

## For Siemens 3D GRASE (quoting David Thomas):
>The way Siemens calculates the background suppression pulse timings is using equation [1] in Matthias' 2005 paper (DOI 10.1002/mrm.20580). For this, you choose a pair of T1 values that you want to suppress: T1opt and 2*T1opt. For 3T, I think they use a T1opt value of 0.7s, so then T1opt represents WM and 2*T1opt is GM. With those two T1 values, you can then use eq [1] to calculate the timing of 2 BS pulses for any given TI. In fact, Siemens choose to null the T1opt and 2*T1opt signals 100ms before readout (i.e. at TI-0.1s), to avoid any issues with signal cancellation due to negative (pre-null point) signals.
>
>So thinking about it again now, given that the timings are arranged so that the GM signal nulls 100ms before the signal readout, all we really need to calculate is how much recovery happens during that 100ms period in order to know the calibration factor between Mctrl and M0 i.e. 1-exp(-0.1/T1GM). If we assume T1GM is 1.4s (as Siemens do for the BS timing calculation - see above), then this gives us a factor of 0.069 i.e. Mctrl = 0.069*M0. This is slightly different to the number I gave to Maurice, due to differences in the assumed T1GM values, but matches pretty well. And it's just a fixed number - no need to change it depending on TI!
>
>One other quick point - the 100ms delay applies to the Siemens product but also worth being aware that the WIP has alternative BS options which changes this delay to get 'better' suppression. This gets chosen on the Contrast - ASL tab of the protocol and is called Suppression Mode: GRAY-WHITE is the standard (as I described it) and GRAY-WHITE STRONG reduces the delay (but I'm not sure what value is used then).

**Comment by HenkMutsaerts** [comment]
## This is what Jan Petr mailed:
* It uses a sliceReadoutTime, tissue T1 is specified (keeping field strength and tissue type out of that), BSup vector comes as an input.

* There's an option for a 90 degree saturation pre-pulse before the Bsup at a given time. But a single pulse. I am not sure what GE exactly does, but I
guess that a single 90 degree flip should be close enough to that?

* I have no idea what is "pre-nulling"

* Since we have the slice-wise, this can indeed be used for 2D EPI - I think I saw an article that has used that already.

* Regarding the Siemens situation - if we know the exact times, this implemented function should work nicely for it as well.

* With Philips, you simply specify the vector of BSup times. It is up to the user to calculate it himself to have whatever suppression he wants.
Typically, this pulse time is given in ms after the start of labeling - so it always has to be adjusted for each PLD and labdur.

**Comment by DaveThoma5** [comment]
Henk has used 'pre-nulling' to describe the approach where the BS timings are calculated to null tissue signal completely, and then a delay is inserted (100ms is typically used on Siemens) to allow the signal to recover a slightly past the null point. The aim for this is to ensure that all magnetisation is +ve, and so avoid any possible issues with the subtraction order being wrong i.e. control-tag will always be the correct way to do it.

**Comment by jan-petr** [comment]
Thank for explaining the 'pre-nulling'. Understood. The current function can easily do that - by simply adding 100ms to the pulses.

**Comment by HenkMutsaerts** [comment]
## Implementation
* I have implemented the function in the M0 quantification, but it is not really clear to me what the function is of the "SaturationPulse", this sounds very general? Can you explain this a bit better (or perhaps it is my lack of knowledge, but still it should be clear to the user how to use this parameter ;) 
* Also, x.Q.SaturationTime is not a BIDS parameter, how should we get this from ASL-BIDS?
* Can you check what you think of this implementation in general? Then we can try this with a single example (e.g. Novice)

## Other comments
* % Sort the BS pulses descending - i.e. from the first to last
"ascending" is from first to last (or is this according to BIDS where we have time to slice instead of time from start of TR?). This should probably be clarified for the non-BIDS reader ;)

* Shall we merge Development/BScalculation with the xASL_quant script? The development one just plots extra right, so the plotting can go optional in this xASL_quant function?

**Comment by HenkMutsaerts** [comment]
## Additional discussion with Jan:
* x.Q.SaturationTime should be x.Q.PresaturationTime
* For tissue T1 use the WM tissue (as we mask everything also & extrapolate the WM M0)
* x.Q.PresaturationTime default to PLD+labdur (PCASL) or PLD (PASL)

**Comment by HenkMutsaerts** [comment]
Did the adaptations, haven't tested it yet.
Can you check the BIDS vs ExploreASL seconds vs ms?
Now I assumed all parameters come from BIDS in seconds, but they may have already been converted (e.g. PLD, LabelingDuration etc), so perhaps I should not do the ./1000 division?

**Comment by jan-petr** [comment]
@HenkMutsaerts 
xASL_quant_M0 like ~121
You divide by the SignalPercentage, but for 2D sequence, the SignalPercentage is a vector and needs to be divided slice by slice.

**Comment by jan-petr** [comment]
> * % Sort the BS pulses descending - i.e. from the first to last
>   "ascending" is from first to last (or is this according to BIDS where we have time to slice instead of time from start of TR?). This should probably be clarified for the non-BIDS reader ;)

Yes - the pulses are given in time before readout, so the first pulse has the highest number - feel free to clarify this.

> * Shall we merge Development/BScalculation with the xASL_quant script? The development one just plots extra right, so the plotting can go optional in this xASL_quant function?

Yes - as discussed - I will do that.

**Comment by jan-petr** [comment]
I made a visualization for the BSup calculation script - feel free to adjust the visual style.
See the syntax for testing, for example:
xASL_quant_BSupCalculation([1780,454],3100, 1664, [0,30,60,90,600],'/home/janpetr/tmp/test.jpg')

@HenkMutsaerts Check also my previous comments about bugs in 2D case of the whole M0 script.

**Comment by HenkMutsaerts** [comment]
## Note
* What shall we do with negative values? Inferior slices could have negative signal because of Bsup, so this can be realistic, but often they are positive, or partly positive. In this test case, the inferior slices were positive.

* How does the figure look (top uncorrected control image, bottom corrected, pseudo-M0).
Note that the values cannot be compared (the bottom one is also quantified as M0).

Before correction there seemed to be a factor 10 for top slice higher than bottom slice (by Bsup recovery), after correction this is 0.6 or even lower because of the negative lowest slice. Of course, if we only use the WM and extrapolate, this should probably be fine.

![Screenshot 2020-08-19 at 17 45 29](https://user-images.githubusercontent.com/27774254/90658363-c9876000-e243-11ea-9a80-fa59e769cf86.png)

The GM CBF comes out high at realistic values, or perhaps a bit high.

![Screenshot 2020-08-19 at 17 43 07](https://user-images.githubusercontent.com/27774254/90658180-8927e200-e243-11ea-816d-1abb1f0ef928.png)

## Test case (Novice study, Philips 2D EPI):
* x.M0 = 'UseControlAsM0';
* x.Q.BackGrSupprPulses>0
* x.Q.TissueT1 defaults to 900 ms (WM T1 @ 3T)
* x.Q.BackgroundSuppressionPulseTime = [1465 315]
* x.readout_dim = 2D
* x.Q.LabelingType = 'CASL' (PCASL)
* x.Q.Initial_PLD = 1525;
* x.Q.LabelingDuration = 1650;
* x.Q.PresaturationTime = 3175;


* x.Q.SliceReadoutTime = 37.1053
* SliceTime =
[0   37.1053   74.2106  111.3159  148.4212  185.5265  222.6318  259.7371  296.8424  333.9477  371.0530  408.1583  445.2636  482.3689  519.4742  556.5795  593.6848  630.7901  667.8954  705.0007  742.1060]

* SignalPercentage = 
[-0.0460   -0.0038    0.0368    0.0757    0.1130    0.1488    0.1832    0.2162    0.2479    0.2782    0.3074    0.3354    0.3622
   0.3880    0.4127    0.4364    0.4592    0.4810    0.5020    0.5221    0.5414]

**Comment by jan-petr** [comment]
@HenkMutsaerts I would change those myself, but lets discuss first to have a consensus and avoid conflicting edits:
* xASL_quant_BSupCalculation.m - line 43 this has to be an error, not a warning - it will crash the code otherwise.
* xASL_quant_BSupCalculation.m - line 48 PresaturationTime<500 - that's not too much, I would set it to 100.
* xASL_quant_BSupCalculation.m - line 52 'Invalid BSupTime of ' num2str(BSupTime) ', seems invalid' - two times 'invalid'
* xASL_quant_M0.m - line  116 - "if strcmp(x.readout_dim, '2D')" -  - better check the length of the SignalPercentage Vector as a condition.
* xASL_quant_M0.m - line  128 - the comment does not fit grammatically.
* Negative values are simple - you take an absolute value of it. Because if the M0 vector is below zero, then it is anyway flipped by 90 degree pulse. They are problematic for ASL and subtractions, but for M0 calculation - no issue.
* The M0 before after looks rather ok - I don't see the range of the histogram, but the peak seems high.
* NOVICE - yes a bit higher, but, what can you easily do - can you use a 2D EPI study with BSUp and separate M0, then you can compare the CBF of the normal M0 and that of BSup-M0 - then we can really compare those... And we can let Maurice test it - he'll has a nice comparison on two different scanners so he is really motivated to fix that :) But of course he needs his BSup timing first.
* For NOVICE - the T1 of WM is rather low - which is OK, but it's different than GM, so we have to be really really sure that we mask out the WM nicely and that this doesn't spoil our M0.
* For general verification - Plot M0 slice profile - mean M0 in WM per slice (after masking, but before smoothing). And plot the profile before and after the correction - then we can have a rough check if the correction is fine. It won't be a straight line, but at least a bit.

**Comment by HenkMutsaerts** [comment]
## Changes
* Did your suggestions
* Changed BsupTime to the full BIDS term BackgroundSuppressionPulseTime
* Added spaces after ','
* Removed unused [x, y, ,~] this is not required
* Reset graph to output as default in M0 QC folder
* Moved the Control image correction as subfunction in _xASL_quant_M0.m_
* Corrected enter in xASL_adm_GetPhilipsScaling

## Discussion points
* Do you mean the 90-degree flip that is done for the readout? If the longitudinal magnetization is negative, this would result in negative transverse magnetization, right? Also, it would make sense to keep this negative, as it would revert the negative subtraction signal in the bottom slice(s)

* Why are all equations in _xASL_quant_BsupCalculation_ matrix multiplications/division & exponents? Should they be non-matrix ones?
* Can you not move all the plotting stuff to the end of the function, or a subfunction, now they are intermittent inside the Bsup calculation (more difficult to read)
* Several locations needed rounding the max(SliceTime)
* changed the colors (green & black), added a title
* Combined the plot with other plots
* What about the vascular component, the CBV should be 2-5%, this didn't get background suppression (fresh inflow). So should we multiply the Bsup effect with 0.95, to account for this?

* This is figure that we create now, for validation/QC, how does this look to you?
![RevertBsupFxControl](https://user-images.githubusercontent.com/27774254/90763721-79fa7000-e2e7-11ea-8bfe-623dcd162e85.jpg)

* Good idea for Maurice to validate this method with the actual M0 image! We could then do this for both 2D EPI & 3D GRASE

* Masking is done pretty well, of course not always foolproof.

**Comment by jan-petr** [comment]
Thanks for the edits. And I like and approve all those did by you.

To answer all the comments above (sorry for not keeping the same structure)
**Discussion points**
* There's no negative transverse magnetization - if that happens then only the phase is different. That's why you need complex subtraction. But for M0, you can really take the absolute value. Of course, you want to be above zero for ASL control/label, that's why Siemens has this 100ms prenulling period to have all values positive, while Philips aims for a nice zero.
* Regarding matrix equations - I took the source from the script with three tissue types, so I kept the matrix operations - but this will not affect the functionality for the scalars.
* Yes, all the plotting is totally independent so it can be grouped at the end - I have no hard opinion on the issue if it's better to group functionality or visualization/calculation.
* Good point about CBV - is that 2-5% in WM as well? Your equation is wrong. It's 2-5% (*0.95) only in full signal, not for the Bsupped signal. For the inferior slices, the bsupcorrection can be 0.001, while the CBV signal much more than 2-5%. The correction of CBV signal has to be based on absolute values and a subtraction from the BSupped-M0 before applying the correction - this correction is different for all slices.
* The figure is awesome - I mean what you do, not how it looks :D After correction for the inferior slices, we get too high values - either because we multiply noise and CBV by division with very low correction values. We have to fix the CBV, account for noise, and avoid correcting for residuals < 0.1 - for example - then we can avoid this horrible peak.
* Yes - let's talk with Maurice.
* OK, about the masking - we can check for outlying values after the correction.

**Comment by HenkMutsaerts** [comment]
M0 = 2.5% CBV + 97.5% WM tissue
Ratio is not 0.01 but 0.025*1+0.97.5*0.01 -> needs validation, perhaps we can take the ratio from NOVICE. 
Otherwise, ignore this.

We will do a few validation experiments for subjects that have both M0 and pseudo-M0 images.

**Comment by HenkMutsaerts** [comment]
ToDo HJ:
/Users/henk/ExploreASL/ASL/Test_EPAD_PseudoM0
1. run structural module
2. copy data to /AnalysisM0 & /AnalysisPseudoM0, but remove M0s of PseudoM0, and run PseudoM0 analysis there (use same commit pipeline for both analyses)
3. copy-paste screen examples, M0 examples & CBF examples
4. Define cutoff below which you exclude slices & extrapolate from other slices

**Comment by jan-petr** [comment]
I will fix several more bugs in the develop branch and then we will need to merge all the hotfix and develop changes to this branch to allow testing.

I will create a new feature branch, cherry pick all the commits to it and delete this old branch.

**Comment by HenkMutsaerts** [comment]
Just checked with David Thomas again, for 3D we would need to make sure that the suppression is not too high (like with the lowest 2D EPI slices). We could get the temporal SNR, and if this is too low we issue a warning on this technique. But you don't want too efficient Bsup anyway, you want e.g. 10% of tissue signal left for MoCo, and to avoid needing a complex subtraction.

**Comment by HenkMutsaerts** [comment]
Let's merge this, but revert the addition of this pseudo-M0 option from the DataParameterTemplate.m.
Then we open a new branch for testing this, in which we also add this option to DataParameterTemplate.m

**Comment by HenkMutsaerts** [comment]
For Yeva (Jan's MSc student) to test the background suppression correction without smoothing:

If you avoid adding `x.M0_conventionalProcessing` to your DataPar.m, `xASL_wrp_ProcessM0` will copy the standard space M0 after quantification but before masking/smoothing.

**Comment by HenkMutsaerts** [comment]
This is fine to be merged, and Jan's student can still work on it for 1.5.0.

**Comment by jan-petr** [comment]
Reverted changes in xASL_io_mediri header so that I don't have to do conflict solving.

Added header changes in xASL_quant_M0 explaining new outputs in x.struct.

Reworked the Background suppression correction so that it works with pulses defined *after* the start of labeling and not before the start of the readout.
