### ISSUE TITLE
Visualization contour overlay for checking registration

### ISSUE THREAD

**Issue by HenkMutsaerts** [ExploreASL/ExploreASL#37]
% Get the images
imgs = spm_select;
% Display them
spm_check_registration(imgs);
% Display contour of 2nd image onto 1st
spm_orthviews('contour','display',2,1)

**Comment by jan-petr** [comment]
OK, I see now this issue here. This is indeed duplicitous to the other one with contours.

Anyway, since I worked on the other already. I propose to close this one.

Regarding the SPM function - I have used our own function on purpose - we have our own visualization scripts. And we have a function to do the distance transform and create contours. I have implemented a very fast algorithm in MEX and this was much faster than the SPM's and Matlab's functions for that.

**Comment by HenkMutsaerts** [comment]
Sounds good, let's close this one then
