### ISSUE TITLE
Reference to field 'SUBJECTS' that does not exist

### ISSUE THREAD

**Issue by longfangithub** [ExploreASL/ExploreASL#41]
hi, ExploreASL was installed with matlab2018b. When a dataset path was input to ExploreASL, the following problems arise: Reference to field 'SUBJECTS' that does not exist. 
error in xASL_Iteration (line 56)
        SelectedSubjects = x.SUBJECTS;

error in ExploreASL_Master (line 99)
        [~, x] = xASL_Iteration(x,'xASL_module_Structural');

Do you have a more detailed user manual?

**Comment by HenkMutsaerts** [comment]
Dear Long Fan,


Thanks for this issue. We have extensive manuals for this though on the [website](www.exploreasl.org), and I suggest you to start with the [WalkThrough](https://docs.google.com/document/d/10OpHiXTxDUtNar-FAQQeq9unS9j0zC4y0X86okK0t_U/edit#heading=h.gjdgxs). The manual can be found on the website as well. Please, otherwise mail me at henkjanmutsaerts@gmail.com or post your question at the ExploreASL Google Groups. I will insert replace the error you got by a warning that suggests you to load a correct DataPar file, containing a correct regular expression as to your subject folders. Then I will close this issue. Also note that this may not be the correct location for questions.

Thanks for noting this,
Best wishes,
Henk

**Comment by HenkMutsaerts** [comment]
Is merged, so closes issue #41
