### ISSUE TITLE
xASL_io_SplitASL does not account for re-runs

### ISSUE THREAD

**Issue by MauricePasternak** [ExploreASL/ExploreASL#433]
First time through, the function will behave as intended and split according to `x.M0PositionInASL4D`. 

Upon attempting re-runs, however, if both ASL4D.nii.gz and ASL4D_Source.nii.gz exist, then no splitting will occur. This behavior prevents users from re-running the ASL module if they accidentally specified an incorrect value for `x.M0PositionInASL4D` the first time around.

Attaching [DataPar.zip](https://github.com/ExploreASL/ExploreASL/files/6159977/DataPar.zip) just in case the input was incorrect (but then it wouldn't have worked the first time...)

**Comment by jan-petr** [comment]
Good catch @MauricePasternak . The issue was the the splitting function was always run at the start of the ASL module. And inside the splitting function, the actual splitting procedure was initiated only when the backup was there and the ASL4D.nii wasn't yet there. This makes sense as you don't want to re-split all the time and waste processing time on splitting already processed data.

Though I agree that what you report is a valid issue and we should address it. My changes are:
1. The splitting function is always run when no steps in the ASL module were yet done. That is on the first time or when none of the lock-files 01, 02, 03 are in place.
2. Inside the splitting function - the splitting procedure is always initiated if ASL-backup is present and the ASL and M0.nii are always rewritten.

@MauricePasternak I hope that this solves your issue. But for obvious reasons, this will only work and redo the splitting if the lock files for the ASL module are removed. Previously it didn't do it even if you did remove them.
@HenkMutsaerts This should not affect the functionality for any current datasets and on normal conditions, this should do exactly the same. The only issue can be if both ASL_Source and ASL are then, then it overwrites them, but that's not a behavior that would be wrong IMHO.
