### ISSUE TITLE
Update docker documentation, and fix workflow on deploy.

### ISSUE THREAD

**Issue by HenkMutsaerts** [ExploreASL/ExploreASL#508]
- [x] 1. Change Source file for documentation to refer to current supported Matlab version in the docker header.
- [x] 2. Abbreviations should be defined, links should be provided (I think I did this now)
- [x] 3. The ExploreASL versioning and how this is updated should be clear. The main ExploreASL Docker should always contain the latest main version.
- [x] 4.  Fix docker workflows in deploy repository.

**Comment by MichaelStritt** [comment]
> 1. The Docker README should include the Matlab version that we used (in the year format), e.g. R2018b. If I remember correctly, we agreed upon using R2018b, but can change to another version if needed; as long as this is transparent.

We have to stick to the version that was used for the compilation. If Jan will compile future releases, we have to update the mcr docker image with his Matlab version.

> 2. Abbreviations should be defined, links should be provided (I think I did this now)

Seems fine 👍 

> 3. The ExploreASL versioning and how this is updated should be clear. The main ExploreASL Docker should always contain the latest main version.

The version number of the docker images was always the same as the GitHub main version. I'd only publish on dockerhub if it works from now on though, since we don't need to publish with two separate providers and we can save the overhead.
![image](https://user-images.githubusercontent.com/46593074/116385652-4a5a1b00-a819-11eb-8afb-f3891d92e1c1.png)

> 4. The ExploreASL beta docker can only be linked to the develop branch, if it is automatically updated to the latest develop merge. Probably the easiest is to delete the develop branch for now.

Delete the develop branch?!?
