### ISSUE TITLE
Quadrupling of backslashes in JSON

### ISSUE THREAD

**Issue by jan-petr** [ExploreASL/ExploreASL#54]
When converting JSONs data_pars from the old format to the new format it escapes the backslashes, but instead of outputting two of them, which is the correct way to do that in JSON '\\' it creates four '\\\\'. This is not a real problem as this is then later corrected when used for a path, but it should still be removed.

Issue reported by Maurice, and discovered in variables: mypath, subjectregexp.

**Comment by HenkMutsaerts** [comment]
So the point is that instead of escaping each '\', it needs to check that it's not '\\' that it's escaping, right?

**Comment by jan-petr** [comment]
> So the point is that instead of escaping each '', it needs to check that it's not '\' that it's escaping, right?

It should escape '\' to create '\\' but it shouldn't escape '\\' to create '\\\\'

**Comment by HenkMutsaerts** [comment]
No this is not correct. '' doesn't need escaping, '\' (mainly in the subject-regexp) needs escaping to '\\' for JSON. But this should avoid escaping '\\'. So the current '\' finding should be replaced by a regexp( ,((?!\)'\')) to find a '\' that is not preceded by another '\'.

While you're at it, can you check the reading of vectors? Currently, [1 1 1] is read correctly but puts it in a vertical vector, rather than keeping it horizontally. The JSON reading for import should probably always do (:)' to always transpose it to a horizontal vector.
