### ISSUE TITLE
Add atlas startup options for mTrial

### ISSUE THREAD

**Issue by HenkMutsaerts** [ExploreASL/ExploreASL#56]
* Precuneous in Hammers atlas -> correct spelling
* Add options to population module
* Create option to specify different atlases (and put MNI structural back to default)
* For mTrial demo, add vascular atlas & HO_cort_CONN

**Comment by MichaelStritt** [comment]
@HenkMutsaerts What do you think about doing it like in commit 619a27a ?

**Comment by MichaelStritt** [comment]
Backwards compatibility should work now. Tested it with the TestDataSet. Should we add all the other atlases to the switch case, too?

**Comment by MichaelStritt** [comment]
Hey @HenkMutsaerts 
my idea was to use a notation like this one to do all atlases in native space:
```
"x": [{
	"name": "ExampleDataSet",
	"subject_regexp": "^Sub-\\d{3}$",
	"Quality": 0,
	"bNativeSpaceAnalysis": 1,
	"Atlases": "{'TotalGM','DeepWM','Hammers','HO_cortex','HO_subcortical'}",
	"AtlasesNativeSpace": 1,
}]
```
And the option to define them as an array:
```
"x": [{
	"name": "ExampleDataSet",
	"subject_regexp": "^Sub-\\d{3}$",
	"Quality": 0,
	"bNativeSpaceAnalysis": 1,
	"Atlases": "{'TotalGM','DeepWM','Hammers','HO_cortex','HO_subcortical'}",
	"AtlasesNativeSpace": [0,0,0,1,1],
}]
```
And for the overall default case you would get Atlases=TotalGM, DeepWM, Hammers and AtlasesNativeSpace=1.

There is still an issue with the HO_cortex and the HO_subcortical in 5a8fa09 ... Can you help me there?

**Comment by HenkMutsaerts** [comment]
* This looks good, except that now _bNativeSpaceAnalysis_ & _AtlasesNativeSpace_ are identical options right? Both note if the atlases are used to obtain ROIs in native space (default is standard space only). I wouldn't differentiate between the atlases that are used for obtaining ROIs in native or standard space, simply 1) option for which atlas(es) to use and 2) option for only standard space or also native space.

* The option for native space is because the standard space is relatively quick, whereas for the native space there needs to be a whole lot of resampling and inverting of flow fields being done. This is also why we shouldn't fallback to native space analysis.

* Also shows that an option needs to be self-explanatory/really clear. Perhaps Jans "bNativeSpaceAnalysis" was not really clear as well, because "analysis" can mean anything. Your "AtlasesNativeSpace" is also not completely clear :)
We should probably have only "bGetAtlasROIsInNativeSpace" or something, do you agree?

* To mention which atlases we use, _"Atlases": "{'TotalGM','DeepWM','Hammers','HO_cortex','HO_subcortical'}"_, is sufficient. Because then you can iterate over the AtlasPath as:

for iAtlas=1:length(Atlases)
    CurrentAtlasPath = AtlasPaths.(Atlases{iAtlas});
end

% if Atlases = cell array containing characters which atlases to analyze
% AtlasPaths has fieldnames that are identical to Atlases, containing the path. E.g. AtlasPaths.TotalGM = fullfile(.....

What do you think?

**Comment by MichaelStritt** [comment]
Sounds good, if i got everything correctly we will have the following system:

- DataParFile options: Atlases & bGetAtlasROIsInNativeSpace
   - **Atlases**: list of atlases you want to use
      - All are analyzed in standard space
      - Default: "Atlases": "{'TotalGM','DeepWM',...}"
   - **bGetAtlasROIsInNativeSpace**: boolean, true or false
      - Also analyze all atlases in native space
      - Default: false

For the implementation I have to check the code again. Overall I think it's a good idea to keep it this simple though ;)

**Comment by MichaelStritt** [comment]
I was trying a few different options with the TestDataSet. There seems to be a problem with the masking or the general workflow of the volumetric analysis of HO_cortex and HO_subcortical. So I have to use x.S.IsVolume & x.S.InputDataStr here, don't I? Do I have to turn off x.S.bMasking?
```
C:\...\test\Population\rMaskSusceptibility_Sub-001.nii missing...
Warning: No susceptibility mask found, using legacy option, no susceptibility masking 
> In xASL_stat_GetROIstatistics (line 544)
```
There are also still some bugs for the native space analysis, too.

**Comment by HenkMutsaerts** [comment]
Is there an overlap in your question here, and what we have solved now for 1.2.1?

**Comment by MichaelStritt** [comment]
I'm not sure, have to test if it crashes. I've almost forgot about this branch...

**Comment by MichaelStritt** [comment]
Hey @HenkMutsaerts  & @jan-petr,

I checked out this code Henk and me wrote a while ago. We had these ideas:

- Introduce the `x.Atlases` field, which is set to `x.Atlases = {'TotalGM','DeepWM','Hammers'};` on default
- Option to include atlases like `HO_cortex `and `HO_subcortical`
- Warning if susceptibility masking was not defined for related atlases
- Option to set `bGetAtlasROIsInNativeSpace` 

I tested it with the TestDataSet using the following settings:

```
{
"x": [{
	"name": "ExampleDataSet",
	"subject_regexp": "^Sub-\\d{3}$",
	"Quality": 0,
	"bGetAtlasROIsInNativeSpace": 0,
	"S":
	{
		"bMasking": "[1 0 0 0]"
	},
	"Atlases": "{'TotalGM','DeepWM','Hammers','HO_cortex','HO_subcortical'}"
}]
}
```

This works quite nicely. The only thing I'm struggling with is the option for the atlases in native space. I personally don't need this, but I guess this should work. Probably a bit stupid, but I think I'm just missing an input field and I just don't generate the `TotalGM` and the `LeftRightPop` for example:

```
Warning: Could not load ...\TestDataSet\analysis\Sub-001\ASL_1\TotalGM.nii 
> In xASL_io_Nifti2Im (line 61)
  In xASL_stat_GetROIstatistics (line 83)
  In xASL_wrp_GetROIstatistics (line 118)
  In xASL_module_Population (line 251)
  In xASL_Iteration>runIteration (line 361)
  In xASL_Iteration (line 100) 
```

```
Warning: Could not load ...\TestDataSet\analysis\Sub-001\ASL_1\LeftRightPop.nii 
> In xASL_io_Nifti2Im (line 61)
  In xASL_stat_GetROIstatistics (line 86)
  In xASL_wrp_GetROIstatistics (line 118)
  In xASL_module_Population (line 251)
  In xASL_Iteration>runIteration (line 361)
  In xASL_Iteration (line 100) 
```

Can you give me a hint on how to fix this? Then we could merge this branch 👍

**Comment by HenkMutsaerts** [comment]
The native space you don't need to test, Jan needs to fix this anyway :) it looks nice. I would not default Hammers as it contains many regions and is not fully free.

What do you mean by the susceptibility masking option? That should be atlas independent

**Comment by MichaelStritt** [comment]
> The native space you don't need to test, Jan needs to fix this anyway :) it looks nice. I would not default Hammers as it contains many regions and is not fully free.

Great, already removed it 👍 

> What do you mean by the susceptibility masking option? That should be atlas independent

I thought so, too, but if I use these input parameters (so no susceptibility masking)...
```

{
	"x": [{
		"name": "ExampleDataSet",
		"subject_regexp": "^Sub-\\d{3}$",
		"Quality": 0,
		"bGetAtlasROIsInNativeSpace": 0,
		"Atlases": "{'TotalGM','DeepWM','Hammers','HO_cortex','HO_subcortical'}"
	}]
}
```

... I get the following error ...

```
Preparing ROI-based mrc1T1_StandardSpace_HOcort_CONN_n=1_21-Nov-2020 statistics:
Expanding ROIs for PVC:100%
Computing ROI data: 100%...\TestDataSet\analysis\Population\rMaskSusceptibility_Sub-001.nii missing...
ERROR: Job iteration terminated!
ans =
    'Undefined function or variable 'VascularMask'.
     Error in xASL_stat_GetROIstatistics (line 611)
                         CurrentMask = CurrentMask & VascularMask;
     Error in xASL_wrp_GetROIstatistics (line 118)
     x = xASL_stat_GetROIstatistics(x); % calculate median CBF/spatial CoV etc per ROI
     Error in xASL_module_Population (line 246)
             xASL_wrp_GetROIstatistics(x);
     Error in xASL_Iteration>runIteration (line 361)
     				[result, x] = jobfn(x); % [result, x] = jobfn(x, job_ex);
     Error in xASL_Iteration (line 100)
     	[bAborted, xOut] = runIteration(dbSettings);
     Error in ExploreASL_Master (line 143)
             [~, x] = xASL_Iteration(x,'xASL_module_Population');'
CONT: but continue with next iteration!
```

**Comment by HenkMutsaerts** [comment]
OK, but that error needs to be dealt with. Susceptibility masking should be automatically selected.Are you sure this isn’t fixed by a comment in develop: I remember fixing this (perhaps for 1.3.0)?Did you try rebasing?Otherwise, I need to fix this.   From: Michael Stritt <notifications@github.com>Date: Saturday, 21 November 2020 at 14:00To: ExploreASL/ExploreASL <ExploreASL@noreply.github.com>Cc: Henk Mutsaerts <henkjanmutsaerts@gmail.com>, Mention <mention@noreply.github.com>Subject: Re: [ExploreASL/ExploreASL] Add atlas startup options for mTrial (#56)The native space you don't need to test, Jan needs to fix this anyway :) it looks nice. I would not default Hammers as it contains many regions and is not fully free.Great, already removed it 👍What do you mean by the susceptibility masking option? That should be atlas independentI thought so, too, but if I use these input parameters (so no susceptibility masking)...  {         "x": [{                "name": "ExampleDataSet",                "subject_regexp": "^Sub-\\d{3}$",                "Quality": 0,                "bGetAtlasROIsInNativeSpace": 0,                "Atlases": "{'TotalGM','DeepWM','Hammers','HO_cortex','HO_subcortical'}"         }] } ... I get the following error ...Preparing ROI-based mrc1T1_StandardSpace_HOcort_CONN_n=1_21-Nov-2020 statistics: Expanding ROIs for PVC:100% Computing ROI data: 100%...\TestDataSet\analysis\Population\rMaskSusceptibility_Sub-001.nii missing... ERROR: Job iteration terminated! ans =     'Undefined function or variable 'VascularMask'.      Error in xASL_stat_GetROIstatistics (line 611)                          CurrentMask = CurrentMask & VascularMask;      Error in xASL_wrp_GetROIstatistics (line 118)      x = xASL_stat_GetROIstatistics(x); % calculate median CBF/spatial CoV etc per ROI      Error in xASL_module_Population (line 246)              xASL_wrp_GetROIstatistics(x);      Error in xASL_Iteration>runIteration (line 361)                                [result, x] = jobfn(x); % [result, x] = jobfn(x, job_ex);      Error in xASL_Iteration (line 100)         [bAborted, xOut] = runIteration(dbSettings);      Error in ExploreASL_Master (line 143)              [~, x] = xASL_Iteration(x,'xASL_module_Population');' CONT: but continue with next iteration! —You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by MichaelStritt** [comment]
> Are you sure this isn’t fixed by a comment in develop: I remember fixing this (perhaps for 1.3.0)?

I recently rebased all the commits from develop to branch #56. 

> Susceptibility masking should be automatically selected.

I can switch out the warning for the automatic selection if you want.

**Comment by MichaelStritt** [comment]
I added the `x.S.bMasking = [1 0 0 0];` as a default value for `HOcort `and `HOsub` in 8d4bcc7, is it ok like this?
Below is a part of the corresponding Population log. It weirdly still complains about missing `rMaskSusceptibility`, but the atlas data seems to be in the Stats folder afterwards.

```
We will apply the following masking:susceptibility mask:
Using subject-specific susceptibility mask
Preparing ROI-based mrc1T1_StandardSpace_HOcort_CONN_n=1_21-Nov-2020 statistics:
Expanding ROIs for PVC:   
Computing ROI data:   
...\Test_Runs\TestDataSet\analysis\Population\rMaskSusceptibility_Sub-001.nii missing...
Converting masks:   
We will apply the following masking:susceptibility mask:
Using subject-specific susceptibility mask
Preparing ROI-based mrc1T1_StandardSpace_HOsub_CONN_n=1_21-Nov-2020 statistics:
Expanding ROIs for PVC:   
Computing ROI data:   
...\Test_Runs\TestDataSet\analysis\Population\rMaskSusceptibility_Sub-001.nii missing...
```

**Comment by HenkMutsaerts** [comment]
It should use proper defaults and work without the masking option, so let’s fix this together this week

**Comment by MichaelStritt** [comment]
Do we also need to fix the issues regarding the native space analysis before merging this for 1.4.0?

**Comment by HenkMutsaerts** [comment]
I wouldn't fix the native space analysis.
But I would clean up these commits, can you rebase the whole thing, and recreate commits such that you only have minimal commits (not all those that are undone by other comments later)? It seems that this branch now has ~30 commits for something that could have been in 5 commits ;) That will allow me to review it, this is currently very tricky. Also for merging to develop, it is helpful if there are just a few clear commits.

For the atlas loading we need to find an easy way to put a cell structure in the JSON (currently it loads only TotalGM and DeepWM for me). This works fine for me.

Now I see the reason for the error at your side: you're trying to run volumetric analyses with the HOcort and somehow it doesn't know that this is not an ASL scan, so it still tries to find ASL-specific masks for the anatomical/structural scans. Check the header of `xASL_wrp_GetROIstatistics.m`:

> %   x.S.ASL                      - true for ASL data, which will take into account its limited resolution
%                                  & regions of poor SNR: apply PVC, PVC expansion, avoid too
%                                  small ROIs, add vascular & susceptibility artifacts masks (OPTIONAL, DEFAULT=true)

So probably when loading anatomical data (`x.S.IsVolume==true` and `mrc1T1`, which is the GM segmentation, not an ASL scan) you should set `x.S.ASL` to false. Does this help? :) I hope the header of `xASL_wrp_GetROIstatistics` is sufficiently clear?

**Comment by HenkMutsaerts** [comment]
@MichaelStritt Great work! 

* I would change the name of “CommercialAtlas” folder to something like “FreeAtlases” (you're indirectly right that the folder "AtlasesNonCommercial" is not clear, could be e.g. "AtlasesNonCommercialOnly" for clarity. Perhaps there is a better name (e.g. AtlasesRestrictedUse?)
* As the pipeline should be read-only, I would extract the tar.gz and store it as .nii.gz
* If an atlas has a large file size, we could discuss first which ones are interesting/helpful
* If the atlas is 4D, which each volume a mask or probability map for a single ROI, I would make them mutually exclusive so we can save them as a single 3D volume with multiple labels (the atlas loading wrappers in the population module allow both). 
* ischar (line 95) -> if this is skipped, we should probably issue a warning, makes debugging easier
* xASL_init_FileSystem: shouldn’t we make this dependent/transparant, by defining the folders containing atlases, and that every NIfTI file in these folders are added, with the identical fieldname as the NifTI filename? 
* I would also create a default for x.S.Atlases at xASL_module_Population line 216 (for modularity). You can move the default setting in ExploreASL_Initialize line 596 here.

* xASL_import_json: we don’t need the Matlab version anymore in this function? There were some errors in this way of getting the Matlab version, which @MDijsselhof is fixing now, this could then be transferred to the general QC function where we get the Matlab version: /ExploreASL/Functions/xASL_qc_CollectSoftwareVersions.m

**Comment by MichaelStritt** [comment]
> I would change the name of “CommercialAtlas” folder to something like “FreeAtlases” (you're indirectly right that the folder "AtlasesNonCommercial" is not clear, could be e.g. "AtlasesNonCommercialOnly" for clarity. Perhaps there is a better name (e.g. AtlasesRestrictedUse?)

Good ideas! I think best practice is probably to store them directly using the license name. I combined it with your last suggestion, since some licenses have no individual name. We can still improve this later on.

> As the pipeline should be read-only, I would extract the tar.gz and store it as .nii.gz

The tar atlases contain GC files and I wasn't sure how to work with those. If you're worried about file size etc., we can keep some of them out of the compiled version.

> ischar (line 95) -> if this is skipped, we should probably issue a warning, makes debugging easier

Then we have to make it a bit more sophisticated, since numeric values and structures are possible at this part of the workflow, too. I added a field check with a warning at the beginning of each loop iteration.

> xASL_init_FileSystem: shouldn’t we make this dependent/transparant, by defining the folders containing atlases, and that every NIfTI file in these folders are added, with the identical fieldname as the NifTI filename?

Hm... I don't know. Could be a more flexible solution, but how often do we change the atlases? And if we use different folders for different licenses, this is getting really troublesome. Additionally it gets more complex if there are file names that are invalid field names. 
We can do this, but do we really need to right now?

> I would also create a default for x.S.Atlases at xASL_module_Population line 216 (for modularity). You can move the default setting in ExploreASL_Initialize line 596 here.

Ok, sure. For me it made more sense the other way round, but I actually don't care about this that much.

> xASL_import_json: we don’t need the Matlab version anymore in this function? 

We were needing it for a while when we supported strings. Now we just make sure that there are only chars and then we don't need a differentiation based on the Matlab version. Worked quite nicely without the version check for me.

**Comment by HenkMutsaerts** [comment]
>> Everything besides the mindboggle atlases seemed to work. ExploreASL asked me to specify the tsv file for the atlas regions. I think I have to define it first, but can you tell me how to integrate the tsv file in the workflow? Getting a GUI request would be pretty bad in the automated workflow. 

All GUI stuff should have a CLI-only fallback. This question is there for user-specific atlases, for which the tsv-file is not yet defined. The tsv-file should contain a single "row"/vector with for each label or atlas volume a string that states the atlas ROI/mask (e.g. "Region1 Region2 Region3" or whatever). Look for the examples in the other atlases (remember that you edited one that had a spelling mistake? :)

>> Additionally, we probably either have to use .nii instead of .nii.gz files for the atlas and/or resample to 1.5mm. Otherwise, ExploreASL always creates the corresponding unpacked and resampled atlas Niftis.

Yes, you're right about the resampling. You can use something like xASL_spm_reslice for this. I found a trick to keep the compression and avoid unzipping, by using the .mat files as well (Matlab uses some compression in them by default). Again, look at the other atlases as example. So the .nii.gz is there then only for the user to open in a viewer, and ExploreASL uses the .mat version.

**Comment by HenkMutsaerts** [comment]
Your other answers above look good!

**Comment by MichaelStritt** [comment]
> All GUI stuff should have a CLI-only fallback. This question is there for user-specific atlases, for which the tsv-file is not yet defined. The tsv-file should contain a single "row"/vector with for each label or atlas volume a string that states the atlas ROI/mask (e.g. "Region1 Region2 Region3" or whatever). Look for the examples in the other atlases (remember that you edited one that had a spelling mistake? :)

Ahhh sorry, I thought I would have to insert the path to the tsv file somewhere in the code, but I just had to add it with the same name. Wasn't clear to me but I think it works now. I'm not 100% sure if I did everything correctly regarding the individual labels, but I can show this to you tomorrow or in the meeting on Thursday.

> Yes, you're right about the resampling. You can use something like xASL_spm_reslice for this. I found a trick to keep the compression and avoid unzipping, by using the .mat files as well (Matlab uses some compression in them by default). Again, look at the other atlases as example. So the .nii.gz is there then only for the user to open in a viewer, and ExploreASL uses the .mat version.

It seems like ExploreASL did it on it's own. We should probably still check if everything works correctly afterwards.

**Comment by MichaelStritt** [comment]
Hey @HenkMutsaerts,
I think everything works now. Now only the DKT31_CMA_labels_MNI152 atlas is added. I removed the other ones in f891546. Additionally, only this atlas and the usual ones are added to the compiled version. In 86ac42d I set this atlas to be the default one for the mTRIAL version. In 661bfe3 I added the resampled version (which ExploreASL generated automatically). db60c13 shows the workflow for the creation of the label file. I'm not 100% sure if this is correct, it just seemed to make sense. Can you have a look or test it? Seemed to work fine on the TestDataSet.

**Comment by MichaelStritt** [comment]
Idea from the meeting on Wednesday:
- Move every atlas to the same folder
- Have one **.nii**, one **.tsv** and one **license.txt** file with the atlas names for every atlas

**Comment by MichaelStritt** [comment]
Hey @HenkMutsaerts, just tested it on the External/TestDataSet.
Everything seems to work fine. Can you (after release 1.4.0) run a test an a population?
I changed the folder structure to be like you described it (one folder, each atlas has 3-4 files: nifti, tsv, lincense text).
I also gzipped the Mindboggle atlas, but it seems to automatically unzip it every time I run the workflow. Do we need to change anything there, too?

**Comment by MichaelStritt** [comment]
Copy of Henks change requests:

* `Development/Mindboggle/get_mindboggle_labels_tsv.m`: would try to keep the same naming practice throughout (which would be something like `xASL_vis_GetMindboggleLabelsTSV.m`)

* Why do we have the `FutureUse` folder? It could go into /develop/, but otherwise best to decide now if we will use it or not (it only takes up Github space). It seems as this is the origin for the Mindboggle atlas to use, so we don’t need to keep this. (Perhaps best to incorporate a reference to these source data somewhere, so we can retrieve them if necessary)

* `External/Atlases/Mindboggle.nii` should be converted to `.nii.gz`, and cloned also into `.nii.mat`, which is a mat-file (which is automatically compressed for uint8 data formats by Matlab), and ExploreASL automatically reads this sidecar instead of unzipping the .gz on disk. We only keep the .nii.gz copy as this is easier to load in lightweight NIfTI viewers such as FSLview or MRICron.

* Also, the labels of `External/Atlases/Mindboggle.nii`should be increasing and adjacent integers, that correspond to the columns in the TSV sidecar. Now there are huge gaps of unused labels (e.g. 50-700, 800-900, 1100-1900). It seems that one hemisphere is multiplied by 2, so you can merge them to have bilateral regions (`xASL_wrp_GetROI*` will split them). Otherwise, this NIfTI is in the correct space, and contains mutually exclusive regions, this is very nice!

* The .txt License files, e.g. `/External/Atlases/HOsub_CONN.txt`, perhaps rename them to e.g. `HOsub_CONN_LICENSE.txt` (like with other license files?), to make it extra clear that this file should be read ;)

* Note that you also committed a chmod (from 755 to 644)… for `External/Atlases/HammersCAT12.txt`. Not a big deal, but probably nicer if all files have similar default permissions.

* External/Atlases/Mindboggle.tsv: sorry, perhaps I didn’t explain this well enough; but this format is invalid. It should be a single row with all ROI names, corresponding to the integer labels in the nii.gz. The cloning for B, L, and R, is done by the `xASL_wrp_GetROI*` functions, the ROIs in the .nii.gz and .tsv sidecar should all be bilateral only. Now you also did this B, L, R cloning in the TSV :) And some ROIs don’t have names?

* Why do we have a separate README folder, instead of keeping those readme.txt as sidecars as well?

* The doc crawler, `README.md` etc, can we not set up that this is processed/edited automatically when merging? (By Github actions)

* `xASL_import_json`: would ensure that if the if-statements are not fulfilled, that you have an alternative (e.g. `warning('this field should be a character array')`; for: line 100 if `ischar(x.(sFields{n})) % Make sure the field is a character array` (and similar throughout)

* `xASL_init_FileSystem:`  `x.P.Atlas.TotalGM                           = fullfile(x.D.MapsSPMmodifiedDir, 'TotalGM.nii');` -> I would standardise this, such that the filenames are always the same as the atlas NIfTI filenames. This makes it easier for everyone (including the users).

* `xASL_vis_CreateVisualFig:` `MaskIn       - cell structure containing 2 binary masks matrices (OPTIONAL, DEFAULT=no masking)` You added “2” here, but they only have to be 2, if ImIn is 2 as well (e.g. a T1w with an image overlay)

* But I don't know what you changed here, or what came from other commits, perhaps better to rebase or cherry-pick, that I only have to review changes you did :)

**Comment by MichaelStritt** [comment]
@HenkMutsaerts 

* `get_mindboggle_labels_tsv.m`: Yeah, so I told this to you guys once in a meeting. I saw in the mindboggle documentation that there are 2035 regions. First I used the existing ExploreASL worklfow without a label file. Then I got this resulting file with 6105 regions (3*2035). Then I mapped these regions to each other. I bet there's a way better way to do this, but I didn't want to mess around with the original NIFTI too much and I didn't know how you do this with the other atlases. Removed the `get_mindboggle_labels_tsv.m` now though 👍 

* `FutureUse` folder: removed it 👍 

* `External/Atlases/Mindboggle.nii` should be converted to `.nii.gz`: Yeah, so I did this, but then the workflow always automatically extracted it somehow. Maybe I did something wrong here?

* There are huge gaps of unused labels (e.g. 50-700, 800-900, 1100-1900) [...] so you can merge them to have bilateral regions (xASL_wrp_GetROI* will split them): can we do this together or can you help me here? 

* `xASL_import_json`: I'm not sure if we are on the same page here. The construct I wrote in lines 100 and following are supposed to search for **all** character arrays written in this way: `"Atlases": "{'TotalGM','DeepWM','Hammers','HO_cortex','HO_subcortical','Mindboggle'}"`. These arrays get converted into correct Matlab cell arrays. If you add warnings here, you will get a warning for every other json field (like numerical fields e.g.).

* `xASL_init_FileSystem`: Nice idea 👍  We sure can implement this.

**Comment by MichaelStritt** [comment]
@HenkMutsaerts 

Thanks for the updated atlas files 👍  I changed the behavior of the atlas part in `init_Filesystem`, so that we can read in every **.nii/.gz** file.

For the **TestDataSet** I tested the current settings with:

```
{
"x": [{
"name": "ExampleDataSet",
"subject_regexp": "^Sub-\\d{3}$",
"Quality": 0,
"S":
{"Atlases": "{'TotalGM','DeepWM','Hammers','HOcort_CONN','HOsub_CONN','Mindboggle'}"}
}]
}
```

I also updated the `io_mTRIAL` script. I checked the options in the **DataPar** template, but I couldn't find what I have to select for the **M0** field if the M0 is in the ASL sequence (`M0PositionInASL4D=1` e.g.). It's in line 80 of `io_mTRIAL`. Is the fixed value from the **DataPar** template for the cases with background suppression the correct fallback solution?

**Comment by MichaelStritt** [comment]
My to-do list:

- Change atlases notation to: `['TotalGM', ...]`
- Remove part for reading this from `json read` if the change above works
- Put all files in the `Atlases` folder
- New Mindboggle name: `Mindboggle_OASIS_DTK31_CMA`
- Change atlas init subfunction to `[x] = ...`
- Iteration over files change `it` to `iFile`
- Use` xASL_fileparts` instead of `fileparts` and remove the extension removal
- Suffix `_LICENSE` for license files
- Change labels in `Mindboggle` nifti according to screenshots from meeting
- Remove fixed M0 values from `io mTRIAL` and if M0 in ASL sequence use `separate_scan` option (add changes in different branch?)

**Comment by MichaelStritt** [comment]
Hey @HenkMutsaerts, thanks again for the help earlier today.

Took me a while to get the reassignment of the labels to work. In the end I used python instead. I didn't want to overwrite the image immediately, which is why I stored the new one as `..._MODIFIED`. Maybe you can have a look if it's okay like that?

![image](https://user-images.githubusercontent.com/46593074/106935787-18ef1900-671c-11eb-8895-c1edd82acf62.png)

Besides that almost everything should be done as well. I removed most of the code from `io_mTRIAL` and just left the updated atlas there.

If you don't want the additional folder in the atlases directory I can change that quickly.

**Comment by HenkMutsaerts** [comment]
Looks very good! Just wondering about the subcortical regions (those with the German Latin ;) it looks now as if they are one single region, but I thought they were multiple different ones?

**Comment by MichaelStritt** [comment]
@HenkMutsaerts 

The label file should work correctly now. In the future we could add a warning message to **ExploreASL**, if the number of regions of the atlas and the labels mismatch. Additionally, I saw that we don't use `xASL_tsvWrite` to write the stats results. If the labels file and the atlas are correct, this isn't a problem, but if someone makes an error in the labels file e.g., **ExploreASL** will return a tsv file with incorrect format (mismatch of number of elements etc.). This wouldn't happen with `xASL_tsvWrite`.

With the **TestDataSet** I still only get n/a for the areas, can you tell me what I'm doing wrong?

**Comment by MichaelStritt** [comment]
5 would be caudate (seems plausible to me [wiki](https://en.wikipedia.org/wiki/Caudate_nucleus))

![image](https://user-images.githubusercontent.com/46593074/107041401-bf8cf580-67c0-11eb-94e6-77e80fc20205.png)

6 would be putamen  (could be correct [wiki](https://en.wikipedia.org/wiki/Putamen))

![image](https://user-images.githubusercontent.com/46593074/107041552-f3681b00-67c0-11eb-80b1-42380325b405.png)

41 would be posterior cingulate (seems plausible to me [wiki](https://en.wikipedia.org/wiki/Posterior_cingulate_cortex))

43 would be precuneus (could be correct [wiki](https://en.wikipedia.org/wiki/Precuneus))

![image](https://user-images.githubusercontent.com/46593074/107041791-36c28980-67c1-11eb-84ba-180f3dfd38cc.png)



![image](https://user-images.githubusercontent.com/46593074/107042064-96b93000-67c1-11eb-8a6a-fae814f32ae5.png)

**Comment by HenkMutsaerts** [comment]
> The label file should work correctly now. In the future we could add a warning message to **ExploreASL**, if the number of regions of the atlas and the labels mismatch. Additionally, I saw that we don't use `xASL_tsvWrite` to write the stats results. If the labels file and the atlas are correct, this isn't a problem, but if someone makes an error in the labels file e.g., **ExploreASL** will return a tsv file with incorrect format (mismatch of number of elements etc.). This wouldn't happen with `xASL_tsvWrite`.

Yes, good idea! Do you want to do this in this issue or create a new issue for this?

**Comment by MichaelStritt** [comment]
> > The label file should work correctly now. In the future we could add a warning message to **ExploreASL**, if the number of regions of the atlas and the labels mismatch. Additionally, I saw that we don't use `xASL_tsvWrite` to write the stats results. If the labels file and the atlas are correct, this isn't a problem, but if someone makes an error in the labels file e.g., **ExploreASL** will return a tsv file with incorrect format (mismatch of number of elements etc.). This wouldn't happen with `xASL_tsvWrite`.
> 
> Yes, good idea! Do you want to do this in this issue or create a new issue for this?

Definitely a separate issue 👍 

> > With the **TestDataSet** I still only get n/a for the areas, can you tell me what I'm doing wrong?
> 
> Difficult to say without any other information ;)

Hm... I'll do a rerun tomorrow.

> The cursor/crosshair in the two subcortical regions point to the thalamus and caudate, instead of caudate and putamen, respectively, as you state. Perhaps re-check with the original atlas values?

Hm... Maybe the index is wrong by 1 element?
Right now I have thalamus_proper=4, caudate=5, putamen=6. But then it probably should be thalamus_proper=5, caudate=6, putamen=7...

**Comment by MichaelStritt** [comment]
@HenkMutsaerts 

I found some bugs in my code. I got some numbers mixed up because there's one region where we seem to have the left but not the right part. Could you check the regions below? Are the correct now? (Sorry, I had to change the colormap in between, so that it's easier for me to find them)

![image](https://user-images.githubusercontent.com/46593074/107155507-13dad580-6979-11eb-8c6e-aeac0a7ae7dd.png)
1 = lateral ventricle

![image](https://user-images.githubusercontent.com/46593074/107155528-3a990c00-6979-11eb-882b-8fe3fbd05017.png)
2 = cerebellum exterior

![image](https://user-images.githubusercontent.com/46593074/107155550-4f759f80-6979-11eb-8074-ec995d2f8b88.png)
3 = cerebellum white matter

![image](https://user-images.githubusercontent.com/46593074/107155598-8fd51d80-6979-11eb-9662-19c2d6bf3d1f.png)
4 = thalamus proper (changed the colormap again)

![image](https://user-images.githubusercontent.com/46593074/107155611-aaa79200-6979-11eb-9e2c-605710df1593.png)
5 = caudate

![image](https://user-images.githubusercontent.com/46593074/107155650-db87c700-6979-11eb-9f05-41f3309bebb7.png)
6 = putamen (changed the colormap again)

![image](https://user-images.githubusercontent.com/46593074/107155673-fa865900-6979-11eb-8848-2f0f2c14df7f.png)
7 = pallidum

**Comment by HenkMutsaerts** [comment]
Yes, this looks good, easier to inspect though if you show them transversely. You know I put a lot of time in ExploreASL that it has a function that creates this for you, with a unique color for each region? ;) Lots of functionality, just difficult to find probably :)

**Comment by MichaelStritt** [comment]
Hey @HenkMutsaerts 

I ran the TestDataSet with these settings to test the Mindboggle Atlas:

```
{
"x": [{
	"name": "ExampleDataSet",
	"subject_regexp": "^Sub-\\d{3}$",
	"Quality": 1,
	"S":
	{"Atlases": ["TotalGM","DeepWM","Hammers","HOcort_CONN","HOsub_CONN","Mindboggle_OASIS_DKT31_CMA"]}
	}]
}
```

Loading the `mean_qCBF_StandardSpace` tsv file gave me these values:

![image](https://user-images.githubusercontent.com/46593074/107204650-34e50a00-69fd-11eb-83e6-0c09013202fa.png)

As you can see, all the regions are n/a. Am I doing something wrong?

There were some warnings during processing: [xASL_module_Population.log](https://github.com/ExploreASL/ExploreASL/files/5942867/xASL_module_Population.log)

If this works we could probably merge 👍

**Comment by MichaelStritt** [comment]
I think there's probably still a minor issue in xASL_stat_GetROIstatistics. I'll try to find it tomorrow.
