### ISSUE TITLE
Release v1.7.0: Manage ExploreASL_Master input path

### ISSUE THREAD

**Issue by MichaelStritt** [ExploreASL/ExploreASL#588]
### Description

`ExploreASL_Master` should accept folders for its first argument.

### Requirements

- Change `ExploreASL_Initialize` so that we can input folders.
- Update `ExploreASL_Master` unit test (`xASL_ut_UnitTest_function_ExploreASL_Master`), so that we can take new use-cases into account.
- Update the documentation [here](https://github.com/ExploreASL/Documentation/tree/master/templates)

### How to test

- Clone the [Testing repository](https://github.com/ExploreASL/Testing) into the same directory where your ExploreASL repository is.
- Run `[UnitTests,UnitTestsTable] = xASL_test_UnitTesting`
- Run `BIDS_fullPipelineTest` or `xASL_test_IntegrationTesting` (which is supposed to become its successor)
- Run `xASL_qc_TestExploreASL`

### Release notes

Release v1.7.0: `ExploreASL_Master` can read folders now and automatically searches for `sourceStructure`, `studyPar` and `dataPar` **JSON** files.

**Comment by jan-petr** [comment]
- I propose the following: Input is a JSON or a directory. It takes the provided JSON and if it recognizes that it's a correct match for the step (based on the content) it takes that. Otherwise it looks in the directory for the JSONs with standard names
- that way, you can still call it with sourceStructure.json, sourceStructure2.json or dataPar-hiQ.json for a specific task. Otherwise, it starts looking for the other script or create dummies
- also - we have to work with the option that it looks inside derivatives/ExploreASL, or work directory with the dataPar.json in the root folder (Legacy)
- if we do it this way - the users won't recognize anything - their old way of calling ExploreASL will still work and we can prompt them with a warning that this is deprecated - this is much much better than change stuff completely and give them an error.
- In a similar way - we should recognize that they have called it with the 1.5.0 options and tell them how to update to 1.6.0 options...

**Comment by MichaelStritt** [comment]
### Meeting Notes

- `dataPar.json`, `studyPar.json` and `sourceStructure.json`: fixed prefixes
- DCM2BIDS: requires `sourceStructure.json`
- BIDS2Legacy: requires `dataset_description.json`

**Comment by MichaelStritt** [comment]
### Intermediate testing

```
================================= TEST RESULTS =================================

              name                  unit          tests        passed
    _________________________    __________    ____________    ______

    'xASL_bids_BIDS2Legacy'      'Function'    [1×2 struct]    true  
    'ExploreASL_Master'          'Function'    [1×8 struct]    true  
    'xASL_io_ExportVTK'          'Function'    [1×5 struct]    true  
    'xASL_test_GetLogContent'    'Function'    [1×2 struct]    true  
    'xASL_io_Nifti2Im'           'Function'    [1×1 struct]    true  
    'xASL_tsvRead'               'Function'    [1×2 struct]    true  
    'xASL_tsvWrite'              'Function'    [1×2 struct]    true  

================================================================================
```
