### ISSUE TITLE
Standardize JSON reading and writing

### ISSUE THREAD

**Issue by HenkMutsaerts** [ExploreASL/ExploreASL#62]
Currently we have xASL_import_json.m, spm_jsonread, spm_jsonwrite for reading and writing of JSONs
We should:
* rename these into xASL_jsonRead & xASL_jsonWrite (like xASL_tsvRead & xASL_tsvWrite)
* move them to SPMmodified/xASL
* change throughout
* xASL_import_json is already a wrapper, that needs cleaning & renaming
* spm_jsonwrite needs a wrapper. We can move some stuff outside of our edited spm_jsonwrite perhaps

NEEDs further discussion. spm_jsonread and spm_jsonwrite work perfectly and they do not really need wrappers because no extra functionality is need - that is an unnecessary overhead. All our JSON files should adhere to the JSON format and they should not need wrappers - this only makes things more complicated and introduce potential errors (several of them fixed already that could have been avoided).

There are one exception to this - the dataPar and studyPar files. There, the content of JSONs need an extra interpretation (removing extra x-level), and fixing (numerical arrays entered as strings). However, the correct JSON fields generated by spm_jsonwrite do not save numerical arrays incorrectly as strings - so this behavior is really needed only for the incorrectly edited studyPar files.

Proposed solution:
1) Use spm_jsonwrite everywhere - that's JSON standard and no wrapper is needed.
2) Use spm_jsonread everywhere where possible - to read automatically and correctly saved JSON files. Go through code and change the calls of xASL_import_json to spm_jsonread where possible.
3) Only leave xASL_import_json for those files that contain strange manually edited constructions in JSON and thus need parsing - like studyPar and DataPar. But make sure that the JSON of those templates and all examples in Flavors, TestDataSet, 10-TestDataset are corrected. 
4) Renames xASL_import_json to xASL_io_ReadDataPar - make a joint function for this with m-files. And make sure to report a warning for all incorrect constructions, so that people edit JSONs correctly and we can phase out this function in the future.

### Release note
JSON i/o unified and using spm_jsonread and spm_jsonwrite for all operations.

**Comment by HenkMutsaerts** [comment]
## ToDo:
1. Replace use of xASL_import_json to spm_jsonread throughout, see which ones fail & requires the conversion of strings to number (which is the only thing xASL_import_json does outside of the DataPar specific functionality)
2. Rename _/Functions/xASL_import_json.m_ to _/Functions/xASL_io_ReadDataPar.m_ & adapt in all code that reads the DataPar JSON-file
3. our spm_jsonwrite.m edits cannot easily be taken out for xASL_spm_jsonwrite

**Comment by HenkMutsaerts** [comment]
When trying to replace xASL_import_json to spm_jsonread, the values are outside the correct range (e.g. factor 1000 too high), @jan-petr this is probably something for you to check.

**Comment by jan-petr** [comment]
xASL_import_json also takes and removes the highest level x in the JSON. So by skipping the wrapper, you come to the 1000 factor, because later, things that are inside the non-removed x are not correctly converted.

I would remove the last commit, keep the wrapper, but clean it indeed.

I like what is stated in the comment from Jul 27, but you comment from 6.9. 3:16PM contradicts that and messes things up. 

Lets revert all commits and comments until the first one and discuss again on what to do.

**Comment by HenkMutsaerts** [comment]
Cannot revert too much:
* spm_jsonwrite cannot be cleaned, this is compiled, and changes are inside spm_jsonwrite, so cannot be "wrapped".
* xASL_import_json wraps around spm_readjson by: 1) converting strings to numbers and 2) removing highest (x) layer. Both are only needed when reading DataPar.json files. So I suggest that you give me a list of functions that need the xASL_import_json instead of spm_readjson, and I will reset this accordingly. 
* renaming xASL_import_json.m to xASL_io_ReadDataPar.m -> do you agree with this renaming?

**Comment by jan-petr** [comment]
In this cleaning - consider also these functions:
- Development/xASL_bids_DataPar2JSON.m
- Functions/xASL_adm_SaveJSON.m
- Functions/xASL_import_json.m
- Functions/xASL_init_ConvertM2JSON.m

**Comment by jan-petr** [comment]
### Finalized solution (taking into account all previous comments
1. Create a new branch based on the current develop
2. Keep only relevant changes from the old branch and redo the previous commits according to the new rules below
3. spm_jsonwrite without wrappers should be used for all saving of JSONs
4. spm_jsonread without wrappers should be used for all loading of JSONs, except the dataPar and studyPar files. There, the content of JSONs need an extra interpretation (removing extra x-level), and fixing (numerical arrays entered as strings) 
5. change the calls of xASL_import_json to spm_jsonread where possible - make sure that legacy files are correctly converted
6. Leave xASL_import_json for those files that contain strange manually edited constructions in JSON and thus need parsing - like studyPar and DataPar. But make sure that the JSON of those templates and all examples in Flavors, TestDataSet, 10-TestDataset are corrected. Rename xASL_import_json to xASL_io_ReadDataPar - make a joint function for this with m-files. And make sure to report a warning for all incorrect constructions, so that people edit JSONs correctly and we can phase out this function in the future.
7. Clean also these functions:
  a. Development/xASL_bids_DataPar2JSON.m
  b. Functions/xASL_adm_SaveJSON.m
  c. Functions/xASL_import_json.m
  d. Functions/xASL_init_ConvertM2JSON.m

**Comment by jan-petr** [comment]
1, 2 DONE. Deleted the old branch, created a new branch, updated the function names in the CustomScripts.

**Comment by jan-petr** [comment]
3, 7b DONE. Saving of JSON is now always done with spm_jsonwrite.m

**Comment by jan-petr** [comment]
7e DONE. Minor clearning of xASL_adm_LoadParms

**Comment by jan-petr** [comment]
4, 5, 7a DONE. Renamed xASL_import_json to xASL_io_ReadDataPar where really needed. Used xASL_adm_LoadParms or spm_jsonread where possible. Two functions moved to an obsolete folder Development/Legacy that is not indexed in the path and is for functions to be phased out - xASL_bids_InsertJSONFields and xASL_bids_DataPar2JSON.

**Comment by jan-petr** [comment]
6, 7d DONE. Now there's a common function to read both DataPar .m and .json. It complains if .m is provided and urges to use .json. And it complains when numerical fields are given as a string - and urges you to give a normal string. 

The only thing I haven't managed is this weird form or providing cell arrays in the JSON. The script can handle this (was programmed previously), but I would like to add a warning so that people stop doing it. But I need a nice example for testing and I can't find any JSON where this would be written in this incorrect way.

**Comment by jan-petr** [comment]
Two notes:
1. xASL_import_json - I have already previously taken out the conversion aspect that changes the field names and units from BIDS to Legacy from this script. So the added value of this script over spm_jsonread was really only in the fact that it corrected weird and messed up JSON entries. That made this whole issue easier to do - and less prone to errors. So we shouldn't have any issues with units because these were already solved in v1.5.0 or v1.4.0
2. There are some errors in BIDS2Legacy, but I want to fix them here and not in a separate issue, because otherwise, I wouldn't be able to really test the whole functionality of the JSON changes. Though this error is also in other branches, so not originating from here. But once fixed, we can decide to move it to another branch for clarity...

**Comment by jan-petr** [comment]
Fix the parsing of the incorrectly entered char array. It is now correctly converted and a warning is issued.
