### ISSUE TITLE
Generalize testing

### ISSUE THREAD

**Issue by MichaelStritt** [ExploreASL/ExploreASL#751]
### Description

We should use the same behavior of the user configured JSON from the `xASL_test_IntegrationTesting `within the `fullBIDSpipeline `test or just move to `xASL_test_IntegrationTesting `completely.

### Requirements

Optional: add feature requirements here

### How to test

Optional: insert description about how to test the code changes here

### Release notes

Required: summarize the changes for the release notes here

**Comment by MichaelStritt** [comment]
Parts of that have been done in this commit 39faccc

**Comment by jan-petr** [comment]
I would indeed mention that part of this has been done in #732, but I would not link this PR - because it is related, but it is not fixing this issue. It only prepares it for it by having this testConfig.json.

If you agree then you can unlink the PR and move the whole issue to 1.9.0 project/milestone, because this can definitively wait.

**Comment by maartenhammer** [comment]
Included in #1247
