### ISSUE TITLE
Import data with ASL dicoms and FLAIR/T1 already in nifti format

### ISSUE THREAD

**Issue by BeatrizPadrela** [ExploreASL/ExploreASL#789]
### Description

Jan and I were discussing today that for DDI dataset, I have the ASL DICOMs, so they are ready for the import module part DCM2NII, but both T1 and FLAIR files are already in nifti format.

Should we adapt our current import module for this case or, as it is kind of specific, should I just copy these niftis to the temp folder before the conversion to BIDS format?

Marked as duplicate - should work fine already, but a script to convert to temp has to be written for each study manually.

**Comment by MichaelStritt** [comment]
I personally wouldn't like to change the import workflow for that. The problem here isn't the import, it's the data. In addition, this should be a super rare case.
I'd suggest to convert the DICOMs using the first import submodule and to write a script which combines the resulting data, so that the remaining import modules can be run afterwards.
