### ISSUE TITLE
xASL_SysMove Error

### ISSUE THREAD

**Issue by MichaelStritt** [ExploreASL/ExploreASL#88]
Hey, I've tried to process a few datasets with the current version of the develop branch. I encountered this error (in the standalone version, but I don't think it's related to being the standalone). Has anyone else seen this error before?

![Annotation 2020-08-14 113659](https://user-images.githubusercontent.com/46593074/90236195-c0048f00-de22-11ea-8108-b25dbd270529.png)

**Comment by MichaelStritt** [comment]
Ok, I've run a few tests now. Seems like it is a problem in the standalone version. The error does not occur when using Matlab directly. I'll try to figure out whats going wrong.

**Comment by jan-petr** [comment]
We do have problems with I/O from time to time. And with the move/copy/delete as well. 

The most important to find out is - is it deterministic? Most frequently, the problem are special characters, space in filenames, characters that should or shouldn't be escaped - these things do differ between OS, file system, datasets, and maybe between normal/compiled. 

Can you try to find out the name of the file and see if there isn't anything wrong with it that causes it to crash - then we can try to find out how to address it.

**Comment by MichaelStritt** [comment]
Hey Jan, I've tested it for the Matlab and the standalone version again. Both tests were done on windows 10. In Matlab it worked and in the standalone it crashed again. The error occurred multiple times. 

[xASL_module_Structural.log](https://github.com/ExploreASL/ExploreASL/files/5074442/xASL_module_Structural.log)
[xASL_module_ASL.log](https://github.com/ExploreASL/ExploreASL/files/5074445/xASL_module_ASL.log)

Do you think the file path is the problem? 

The error happens here (line 78 of xASL_Move):
```xASL_SysMove(SrcPath, DstPath, bOverwrite);```

**Comment by jan-petr** [comment]
First idea - try changing the directory from "Done in standalone" to "DoneInStandalone" - that's potentially the most risky part.

If that's the case, we need to escape the spaces - at least in the standalone version or use "".

Quite possible that the Matlab/compiled version handles this a bit differently, so that it only shows as an error for the compiled version.

**Comment by MichaelStritt** [comment]
Good idea, thanks! Will test it and let you know later.

**Comment by MichaelStritt** [comment]
I think you were right Jan. Now it seems to work. Do you know where in the code we have to escape the spaces?

**Comment by jan-petr** [comment]
xASL_SysMove.m Line 43,44 fixes this for Linux. So for Windows, you want to add something similar to line 56.

The best would be to take the xASL_adm_UnixPath function and turn it into a general function, that either runs the Linux branch or Windows branch.

Before we do that, can you please test a few things. Line 46 escapes the spaces - can you please test if (by calling this inside sysmove resolves the problem and if such a solution can be applied to both Windows and windows+compilation? Also - can you test if this is a problem for both xASL_SysCopy and xASL_delete, or not?

@HenkMutsaerts do you agree?

**Comment by MichaelStritt** [comment]
This totally makes sense. That's also the reason why it worked for xASL docker, because it is linux based.

I'm implementing it right now, but testing could take a while with the whole compilation process.

**Comment by MichaelStritt** [comment]
Escaping spaces weirdly doesn't help. Will keep you updated.

**Comment by MichaelStritt** [comment]
The test is still running, but it seems as if it works with the default Matlab move function.

This is how I would do it right now:
```
%% Start moving
if isunix
    ...
elseif ispc
    if isdeployed
        % Deployed mode
        fprintf('Source path: \t\t%s\n',SrcPath);
        fprintf('Destination path: \t%s\n',DstPath);
        [~,~,~] = movefile(SrcPath,DstPath,'f');
    else
        % Normal windows mode
        if bForce
            strforce = '/Y';
        else
            strforce = [];
        end
        [status,result] = system(['move ' strforce ' ' SrcPath ' ' DstPath]);
        if bSourceCheck && status~=0
            error('Error moving %s to %s: %s', SrcPath, DstPath, result);
        end
    end
else
    ...
end
```

**Comment by jan-petr** [comment]
Looks like a good solution to me!
You can probably omit "[~,~,~] =" without changing the functionality, right?
Also, the fprintf is probably not necessary in the final version, since no message is printed in the other cases.

Can you edit and commit in a new feature branch? Unless you really need to have it in the release 1.2.0.

**Comment by MichaelStritt** [comment]
Fixed #88 with recent rebase

**Comment by HenkMutsaerts** [comment]
Sorry that I see this only now, but two questions:
* _movefile_ now always overwrites (i.e. the 'f') option, whereas this needs to be only done if _bForce_
* we don't capture the error anymore
* SysMove was created to bypass the inefficient _movefile_ from Matlab. While this quick fix is fine for now, we should ideally revert this to using _move_, and A) encourage using underscores instead of whitespaces B) find out how to escape whitespace in Windows, which should be the same irregardless of deployment.

Also: we decided to only deploy in Unix, but this doesn't read like good practice.

see [HERE](https://superuser.com/questions/279008/how-do-i-escape-spaces-in-command-line-in-windows-without-using-quotation-marks) for a solution: using carets ^ for escaping, or quote marks as part of the path "

**Comment by HenkMutsaerts** [comment]
Actually, this issue can be generalized: all calls to Windows system/CLI may have issues with whitespaces or other "relatively illegal" characters, that we could manage as we do with xASL_adm_UnixPath. Why don't we create a xASL_system function that manages this?
