### ISSUE TITLE
Move log files to log directory

### ISSUE THREAD

**Issue by HenkMutsaerts** [ExploreASL/ExploreASL#930]
### Description

`derivatives/ExploreASL/log` contains only import log files, this is potentially confusing

### Requirements

Can we move the log files to the log directory?

### How to test

Optional: insert description about how to test the code changes here

### Release notes

This is a follow-up for import revamp #799, so in the release, this should be added to this issue.

**Comment by MichaelStritt** [comment]
The main reason was that we have an import log for each subject in derivatives, but there are no dedicated subject directories in derivatives (only sub_ses).

I'd suggest to start working on the derivatives structure, so that we are closer to bids. It should become sub_<sub-id>/ses_<ses-id> instead of sub_<sub-id>_<ses-number>, right?

We can easily move the other logs there too, but then we have to give them more specific names (sub_<sub-id>_ses_<ses-id>_xASL_module_<module>.log e.g.)

For me this would be moving forward instead of just renaming temporarily.
